function GUI_Template(varargin)

%%%%%%%%%%%%%%%%%%%%%
%Create GUI Template%
%%%%%%%%%%%%%%%%%%%%%

%Check if window already exists
if ~isempty(findobj('Tag','OpenFresco Quick Start'))
   figure(findobj('Tag','OpenFresco Quick Start'));
   return
end

fig_color = [0.1 0.4 0.6];
panel_color = [0.3 0.5 0.7];

%Main Figure
SS = get(0,'screensize');
f = figure('Visible','off',...
           'Name','OpenFresco Quick Start',...
           'NumberTitle','off',...
           'MenuBar','none',...
           'Tag','OpenFresco Quick Start',...
           'Color',fig_color,...
           'Position',[0 0 SS(3) SS(4)],...
           'CloseRequestFcn',@Quit_Program);
       
%Menubar
Menu(1) = uimenu('Position',1,'Label','File');
Menu(2) = uimenu(Menu(1),'Position',1,'Label','Load', ...
   'Callback','MenuBar(''load'')');
Menu(3) = uimenu(Menu(1),'Position',2,'Label','Save', ...
   'Callback','MenuBar(''save'')');
Menu(4) = uimenu(Menu(1),'Position',3,'Label','Quit',...
   'Callback',@Quit_Program);



%Sidebar Tabs
Sidebar(1) = uibuttongroup('Parent',f,...
    'BackgroundColor',panel_color,...
    'Position',[0.01 .35 .1 .5]);
         tbh1 = uicontrol(Sidebar(1),'Style','togglebutton',...
             'String','Structure',...
             'Units','normalized',...
             'Tag','Struct',...
             'Position',[0.08 0.81 0.84 0.16]);
         tbh2 = uicontrol(Sidebar(1),'Style','togglebutton',...
             'String','Ground Motions',...
             'Units','normalized',...
             'Position',[0.08 0.62 0.84 0.16]);
         tbh3 = uicontrol(Sidebar(1),'Style','togglebutton',...
             'String','Experimental Setup',...
             'Units','normalized',...
             'Position',[0.08 0.43 0.84 0.16]);
         tbh4 = uicontrol(Sidebar(1),'Style','togglebutton',...
             'String','Experimental Control',...
             'Units','normalized',...
             'Position',[0.08 0.24 0.84 0.16]);
         tbh5 = uicontrol(Sidebar(1),'Style','togglebutton',...
             'String','Analysis',...
             'Units','normalized',...
             'Position',[0.08 0.03 0.84 0.16]);
         align([tbh1 tbh2 tbh3 tbh4 tbh5],'None','Fixed',12);
         set(Sidebar(1),'SelectionChangeFcn',@template_toggle_Callback);
         set(Sidebar(1),'SelectedObject',[]);

Sidebar(2) = uicontrol('Parent',f,...
    'Style','pushbutton',...
    'String','User Tips',...
    'Units','normalized',...
    'BackgroundColor',panel_color,...
    'Callback','Links(''User Tips'')',...
    'Position',[0.01 0.30 0.1 0.03]);

Sidebar(3) = uibuttongroup('Parent',f,...
    'BackgroundColor',panel_color,...
    'Visible','off',...
    'Position',[0.01 .05 .1 .23]);
         Sidebar(4) = uicontrol(Sidebar(3),'Style','togglebutton',...
             'String','Start',...
             'BackgroundColor',[0 0.8 0],...
             'Units','normalized',...
             'Position',[0.08 0.66 0.84 0.3]);
         Sidebar(5) = uicontrol(Sidebar(3),'Style','togglebutton',...
             'String','Pause',...
             'BackgroundColor',[1 1 0],...
             'Units','normalized',...
             'Position',[0.08 0.34 0.84 0.3]);
         Sidebar(6) = uicontrol(Sidebar(3),'Style','togglebutton',...
             'String','Stop',...
             'BackgroundColor',[0.8 0 0],...
             'Units','normalized',...
             'Position',[0.08 0.03 0.84 0.3]);
         align([Sidebar(4) Sidebar(5) Sidebar(6)],'None','Fixed',3);
         set(Sidebar(3),'SelectionChangeFcn','Analysis(''choose option'')');
         set(Sidebar(3),'SelectedObject',[]);
         
%Main Display Panel
ph_Main = uipanel('Parent',f,...
    'BackgroundColor',panel_color,...
    'Position',[0.12 0 0.87 1]);

% set(f, 'Visible','on');

A = axes('Parent',ph_Main,'Position',[0 0 1 1]);
imagesc(imread('greyGradient.png'));
set(A,'XTick',[],'YTick',[]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%         
%Create Structure Page%
%%%%%%%%%%%%%%%%%%%%%%%

%Title       
Struct(1) = uicontrol(ph_Main,'Style','text',...
    'String','Structural Properties',...
    'FontSize',20,...
    'Units','normalized',...
    'ForegroundColor',[1 1 1],...
    'BackgroundColor',[0.3 0.5 0.7],...
    'Position',[0.3 0.92 0.4 0.04],...
    'Visible','off');                      

%Image Button Group       
Struct(2) = uibuttongroup('Parent',ph_Main,...
    'Title','Select Structure Type',...
    'BackgroundColor',panel_color,...
    'Position',[0.1 .45 .8 .45],...
    'Visible','off');
         Struct(3) = uicontrol(Struct(2),'Style','togglebutton',...
             'String','1 DOF',...
             'Units','normalized',...
             'Position',[0.025 0.15 0.3 0.7]);
         Struct(4) = uicontrol(Struct(2),'Style','togglebutton',...
             'String','2 DOF A',...
             'Units','normalized',...
             'Position',[0.35 0.15 0.3 0.7]);
         Struct(5) = uicontrol(Struct(2),'Style','togglebutton',...
             'String','2 DOF B',...
             'Units','normalized',...
             'Position',[0.675 0.15 0.3 0.7]);
         set(Struct(2),'SelectionChangeFcn','Structure(''choose DOF'')');
         set(Struct(2),'SelectedObject',[]);

%1 DOF Options                    
Struct(6) = uipanel('Parent',ph_Main,...
    'Position',[0.12 0.35 0.24 0.05],...
    'Visible','off');
         st_Struct_m1 = uicontrol(Struct(6),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','m',...
             'Position',[0.025 0.1 0.05 0.5]);
         Struct(7) = uicontrol(Struct(6),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','Enter mass here',...
             'Position',[0.1 0.1 0.8 0.5],...
             'Tag','Mass',...
             'Callback','Structure(''mass_input'')');
         m1_help = uicontrol(Struct(6),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString','Input a numeric mass value',...
             'Position',[0.925 0.1 0.05 0.5]);
Struct(8) = uipanel('Parent',ph_Main,...
    'Position',[0.12 0.05 0.24 0.28],...
    'Visible','off');      
         st_Struct_k1 = uicontrol(Struct(8),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','k',...
             'Position',[0.025 0.77 0.05 0.1]);
         Struct(9) = uicontrol(Struct(8),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','Enter stiffness here',...
             'Position',[0.1 0.77 0.8 0.1],...
             'Tag','Stiffness',...
             'Callback','Structure(''stiffness_input'')');
         k1_help = uicontrol(Struct(8),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString','Input a numeric stiffness value',...
             'Position',[0.925 0.77 0.05 0.1]);
         Struct(10) = uicontrol(Struct(8),'Style','pushbutton',...
             'String','Calculate T',...
             'Units','normalized',...
             'FontSize',10,...
             'Position',[0.1 0.55 0.8 0.1],...
             'Callback','Structure(''period_calc'')');
         Struct(11) = uicontrol(Struct(8),'Style','text',...
             'Units','normalized',...
             'String','Period',...
             'FontSize',10,...
             'Position',[0.1 0.35 0.8 0.1],...
             'Tag','Period');
         Struct(12) = uicontrol(Struct(8),'Style','popupmenu',...
             'String',{'Damping Type: ','Stiffness Proportional','Mass Proportional'},...
             'Value',1,...
             'Units','normalized',...
             'FontSize',10,...
             'Position',[0.1 0.2 0.8 0.1],...
             'Callback','Structure(''choose damping'')');
         Struct(13) = uicontrol(Struct(8),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','zeta',...
             'Position',[0.1 0.05 0.8 0.1],...
             'Callback','Structure(''damping_input'')');
         Damp1_help = uicontrol(Struct(8),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('Input damping value as a decimal. For\nexample type 0.05 for 5%% damping.'),...
             'Position',[0.925 0.05 0.05 0.1]);
                     
%2 DOF A Options                      
Struct(14) = uipanel('Parent',ph_Main,...
    'Position',[0.38 0.35 0.24 0.05],...
    'Visible','off');
         st_Struct_m2A = uicontrol(Struct(14),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','M',...
             'Position',[0.025 0.1 0.05 0.5]);
         Struct(15) = uicontrol(Struct(14),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','[m1 0; 0 m2]',...
             'Position',[0.1 0.1 0.8 0.5],...
             'Callback','Structure(''mass_input'')');
         m2_help = uicontrol(Struct(14),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('Input a matrix of mass values\nin the form [mass1 0; 0 mass2]'),...
             'Position',[0.925 0.1 0.05 0.5]);
Struct(16) = uipanel('Parent',ph_Main,...
    'Position',[0.38 0.05 0.24 0.28],...
    'Visible','off');
         st_Struct_k2A = uicontrol(Struct(16),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','K',...
             'Position',[0.025 0.77 0.05 0.1]);
         Struct(17) = uicontrol(Struct(16),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','[k11 k12; k21 k22]',...
             'Position',[0.1 0.77 0.8 0.1],...
             'Callback','Structure(''stiffness_input'')');
         k2_help = uicontrol(Struct(16),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('Input a matrix of stiffness values\nin the form [k11 k12; k21 k22]\nwhere k12 = k21'),...
             'Position',[0.925 0.77 0.05 0.1]);
         Struct(18) = uicontrol(Struct(16),'Style','pushbutton',...
             'String','Calculate T',...
             'Units','normalized',...
             'FontSize',10,...
             'Position',[0.1 0.55 0.8 0.1],...
             'Callback','Structure(''period_calc'')');
         Struct(19) = uicontrol(Struct(16),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','Period',...
             'Position',[0.1 0.35 0.8 0.1]);
         Struct(20) = uicontrol(Struct(16),'Style','popupmenu',...
             'String',{'Damping Type: ','Stiffness Proportional','Mass Proportional','Rayleigh'},...
             'Value',1,...
             'Units','normalized',...
             'FontSize',10,...
             'Position',[0.1 0.2 0.8 0.1],...
             'Callback','Structure(''choose damping'')');
         Struct(21) = uicontrol(Struct(16),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','zeta',...
             'Position',[0.1 0.05 0.8 0.1],...
             'Callback','Structure(''damping_input'')');
         Damp2_help = uicontrol(Struct(16),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('Input damping value as a decimal. For\nexample type 0.05 for 5%% damping.\nFor Rayleigh damping, two values\nare required in the form [zeta1 zeta2]'),...
             'Position',[0.925 0.05 0.05 0.1]);
         
%2 DOF B Options                      
Struct(22) = uipanel('Parent',ph_Main,...
    'Position',[0.64 0.35 0.24 0.05],...
    'Visible','off');
       st_Struct_m2B = uicontrol(Struct(22),'Style','text',...
           'Units','normalized',...
           'FontSize',10,...
           'String','M',...
           'Position',[0.025 0.1 0.05 0.5]);
       Struct(23) = uicontrol(Struct(22),'Style','text',...
           'Units','normalized',...
           'FontSize',10,...
           'String','[m1 0; 0 m2]',...
           'Position',[0.1 0.1 0.8 0.5],...
           'Callback','Structure(''mass_input'')');
       m3_help = uicontrol(Struct(22),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('Input a matrix of mass values\nin the form [mass1 0; 0 mass2]'),...
             'Position',[0.925 0.1 0.05 0.5]);
Struct(24) = uipanel('Parent',ph_Main,...
    'Position',[0.64 0.05 0.24 0.28],...
    'Visible','off');
       st_Struct_k2B = uicontrol(Struct(24),'Style','text',...
           'Units','normalized',...
           'FontSize',10,...
           'String','K',...
           'Position',[0.025 0.77 0.05 0.1]);
       Struct(25) = uicontrol(Struct(24),'Style','text',...
           'Units','normalized',...
           'FontSize',10,...
           'String','[k11 k12; k21 k22]',...
           'Position',[0.1 0.77 0.8 0.1],...
           'Callback','Structure(''stiffness_input'')');
       k3_help = uicontrol(Struct(24),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('Input a matrix of stiffness values\nin the form [k11 k12; k21 k22]\nwhere k12 = k21'),...
             'Position',[0.925 0.77 0.05 0.1]);
       Struct(26) = uicontrol(Struct(24),'Style','pushbutton',...
           'String','Calculate T',...
           'FontSize',10,...
           'Units','normalized',...
           'Position',[0.1 0.55 0.8 0.1],...
           'Callback','Structure(''period_calc'')');
       Struct(27) = uicontrol(Struct(24),'Style','text',...
           'Units','normalized',...
           'FontSize',10,...
           'String','Period',...
           'Position',[0.1 0.35 0.8 0.1]);
       Struct(28) = uicontrol(Struct(24),'Style','popupmenu',...
           'String',{'Damping Type: ','Stiffness Proportional','Mass Proportional','Rayleigh'},...
           'Value',1,...
           'Units','normalized',...
           'FontSize',10,...
           'Position',[0.1 0.2 0.8 0.1],...
           'Callback','Structure(''choose damping'')');
       Struct(29) = uicontrol(Struct(24),'Style','text',...
           'Units','normalized',...
           'FontSize',10,...
           'String','zeta',...
           'Position',[0.1 0.05 0.8 0.1],...
           'Callback','Structure(''damping_input'')');
       Damp3_help = uicontrol(Struct(24),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('Input damping value as a decimal. For\nexample type 0.05 for 5%% damping.\nFor Rayleigh damping, two values\nare required in the form [zeta1 zeta2]'),...
             'Position',[0.925 0.05 0.05 0.1]);

       
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%         
%Create Ground Motions Page%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Title
GM(1) = uicontrol(ph_Main,'Style','text',...
    'String','Ground Motions',...
    'FontSize',20,...
    'ForegroundColor',[1 1 1],...
    'BackgroundColor',[0.3 0.5 0.7],...
    'Units','normalized',...
    'Position',[0.3 0.92 0.4 0.04],...
    'Visible','off');

%DOF 1 Ground Motion Options                     
GM(2) = uipanel('Parent',ph_Main,...
    'Position',[0.2 0.65 0.25 0.25],...
    'Tag','Direction 1',...
    'Visible','off');
         st_GM_Xlabel = uicontrol(GM(2),'Style','text',...
             'Units','normalized',...
             'String','DOF 1',...
             'FontSize',10,...
             'FontWeight','bold',...
             'Position',[0.45 0.85 0.15 0.1]);
         st_GM_Xfile = uicontrol(GM(2),'Style','text',...
             'Units','normalized',...
             'String','File:',...
             'Position',[0.03 0.7 0.1 0.1]);
         GM(3) = uicontrol(GM(2),'Style','edit',...
             'Units','normalized',...
             'String','...',...
             'BackgroundColor',[1 1 1],...
             'Tag','GM(3)',...
             'Position',[0.25 0.7 0.43 0.1],...
             'Callback','GroundMotions(''manual load'')');
         pbh_GM_Xbrowse = uicontrol(GM(2),'Style','pushbutton',...
             'Units','normalized',...
             'String','...',...
             'Tag','pbh_GM_Xbrowse',...
             'Position',[0.71 0.7 0.1 0.1],...
             'Callback','GroundMotions(''load'')');
         GM_help = uicontrol(GM(2),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('You can find ground motions from PEER at\nhttp://peer.berkeley.edu/nga/\nfrom CESMD at\nhttp://www.strongmotioncenter.org/\nor you can upload your own file.\nNote that unrecognized formats require\nthe time step to be input manually.'),...
             'Position',[0.85 0.7 0.05 0.1]);
         %Divide Frame
         Height = 0.005;
         uicontrol(GM(2),'Style','frame', ...
             'Units','normalized', ...
             'BackgroundColor',[0 0 0],...
             'ForegroundColor',[0 0 0],...
             'Position',[0.00 0.62 1.00 Height]);
         st_GM_Xscale = uicontrol(GM(2),'Style','text',...
             'Units','normalized',...
             'String','Scale Factors',...
             'FontSize',10,...
             'FontWeight','bold',...
             'Position',[0.1 0.45 0.8 0.1]);
         st_GM_Xamp = uicontrol(GM(2),'Style','text',...
             'Units','normalized',...
             'String','Amplitude',...
             'Position',[0.01 0.28 0.2 0.1]);
         GM(4) = uicontrol(GM(2),'Style','edit',...
             'Units','normalized',...
             'String','386.1',...
             'BackgroundColor',[1 1 1],...
             'Tag','edit_amp1',...
             'Position',[0.25 0.3 0.56 0.1],...
             'Callback','GroundMotions(''scale'')');
         agScale_help = uicontrol(GM(2),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('The ground motion record is automatically\nsclaed by gravity in units of in/s^2.'),...
             'Position',[0.85 0.3 0.05 0.1]);
         st_GM_Xdt = uicontrol(GM(2),'Style','text',...
             'Units','normalized',...
             'String','Time',...
             'Position',[0.03 0.13 0.125 0.1]);
         GM(5) = uicontrol(GM(2),'Style','edit',...
             'Units','normalized',...
             'String','1',...
             'BackgroundColor',[1 1 1],...
             'Tag','edit_time1',...
             'Position',[0.25 0.15 0.56 0.1],...
             'Callback','GroundMotions(''scale'')');
         GM(6) = uicontrol(GM(2),'Style','pushbutton',...
             'Units','normalized',...
             'String','Apply Scale Factors',...
             'Tag','scale_1',...
             'Position',[0.33 0.03 0.4 0.1],...
             'Callback','GroundMotions(''scale'')');
         GM(7) = axes('Parent',ph_Main,'Position',[0.15 0.45 0.35 0.15],...
             'Tag','a_GM_Xag','Visible','off','NextPlot','replacechildren');
             xlabel(GM(7),'Time (s)');
             ylabel(GM(7),'ag');
         GM(8) = axes('Parent',ph_Main,'Position',[0.15 0.25 0.35 0.15],...
             'Tag','a_GM_XSa','Visible','off','NextPlot','replacechildren','XTickLabel',[]);
             ylabel(GM(8),'Sa');         
         GM(9) = axes('Parent',ph_Main,'Position',[0.15 0.08 0.35 0.15],...
             'Tag','a_GM_XSd','Visible','off','NextPlot','replacechildren');     
             xlabel(GM(9),'Period (s)');
             ylabel(GM(9),'Sd');         

%DOF 2 Ground Motion Options
GM(10) = uipanel('Parent',ph_Main,...
    'Position',[0.65 0.65 0.25 0.25],...
    'Tag','Direction 2',...
    'Visible','off');
         sty = uicontrol(GM(10),'Style','text',...
             'Units','normalized',...
             'String','DOF 2',...
             'FontSize',10,...
             'FontWeight','bold',...
             'Position',[0.45 0.85 0.15 0.1]);
         st_GM_Yfile = uicontrol(GM(10),'Style','text',...
             'Units','normalized',...
             'String','File:',...
             'Position',[0.03 0.7 0.1 0.1]);
         GM(11) = uicontrol(GM(10),'Style','edit',...
             'Units','normalized',...
             'String','...',...
             'BackgroundColor',[1 1 1],...
             'Tag','GM(10)',...
             'Position',[0.25 0.7 0.43 0.1],...
             'Callback','GroundMotions(''manual load'')');
         pbh_GM_Ybrowse = uicontrol(GM(10),'Style','pushbutton',...
             'Units','normalized',...
             'String','...',...
             'Tag','pbh_GM_Ybrowse',...
             'Position',[0.71 0.7 0.1 0.1],...
             'Callback','GroundMotions(''load'')');
         GM_help = uicontrol(GM(10),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('You can find ground motions from PEER at\nhttp://peer.berkeley.edu/nga/\nfrom CESMD at\nhttp://www.strongmotioncenter.org/\nor you can upload your own file.\nNote that unrecognized formats require\nthe time step to be input manually.'),...
             'Position',[0.85 0.7 0.05 0.1]);
         %Divide Frame
         Height = 0.005;
         uicontrol(GM(10),'Style','frame', ...
             'Units','normalized', ...
             'BackgroundColor',[0 0 0],...
             'ForegroundColor',[0 0 0],...
             'Position',[0.00 0.62 1.00 Height]);
         st_GM_Yscale = uicontrol(GM(10),'Style','text',...
             'Units','normalized',...
             'String','Scale Factors',...
             'FontSize',10,...
             'FontWeight','bold',...
             'Position',[0.1 0.45 0.8 0.1]);
         st_GM_Yamp = uicontrol(GM(10),'Style','text',...
             'Units','normalized',...
             'String','Amplitude',...
             'Position',[0.01 0.28 0.2 0.1]);
         GM(12) = uicontrol(GM(10),'Style','edit',...
             'Units','normalized',...
             'String','386.1',...
             'BackgroundColor',[1 1 1],...
             'Tag','edit_amp2',...
             'Position',[0.25 0.3 0.56 0.1],...
             'Callback','GroundMotions(''scale'')');
         agScale_help = uicontrol(GM(10),'Style','text',...
             'Units','normalized',...
             'FontSize',10,...
             'String','?',...
             'ToolTipString',sprintf('The ground motion record is automatically\nsclaed by gravity in units of in/s^2.'),...
             'Position',[0.85 0.3 0.05 0.1]);
         st_GM_Ydt = uicontrol(GM(10),'Style','text',...
             'Units','normalized',...
             'String','Time',...
             'Position',[0.03 0.13 0.125 0.1]);
         GM(13) = uicontrol(GM(10),'Style','edit',...
             'Units','normalized',...
             'String','1',...
             'BackgroundColor',[1 1 1],...
             'Tag','edit_time2',...
             'Position',[0.25 0.15 0.56 0.1],...
             'Callback','GroundMotions(''scale'')');
         GM(14) = uicontrol(GM(10),'Style','pushbutton',...
             'Units','normalized',...
             'String','Apply Scale Factors',...
             'Tag','scale_2',...
             'Position',[0.33 0.03 0.4 0.1],...
             'Callback','GroundMotions(''scale'')');
         GM(15) = axes('Parent',ph_Main,'Position',[0.6 0.45 0.35 0.15],...
             'Tag','a_GM_Yag','Visible','off','NextPlot','replacechildren');
             xlabel(GM(15),'Time (s)');
             ylabel(GM(15),'ag');
         GM(16) = axes('Parent',ph_Main,'Position',[0.6 0.25 0.35 0.15],...
             'Tag','a_GM_YSa','Visible','off','XTickLabel',[],'NextPlot','replacechildren');
             ylabel(GM(16),'Sa');         
         GM(17) = axes('Parent',ph_Main,'Position',[0.6 0.08 0.35 0.15],...
             'Tag','a_GM_YSd','Visible','off','NextPlot','replacechildren');
             xlabel(GM(17),'Period (s)');
             ylabel(GM(17),'Sd');         
                      

         
         
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%         
%Create Experimental Setup Page%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Title
ExpSetup(1) = uicontrol(ph_Main,'Style','text',...
    'String','Experimental Setup',...
    'FontSize',20,...
    'Units','normalized',...
    'ForegroundColor',[1 1 1],...
    'BackgroundColor',panel_color,...
    'Position',[0.3 0.92 0.4 0.04],...
    'Visible','off');

%Image Button Group       
ExpSetup(2) = uibuttongroup('Parent',ph_Main,...
    'Title','Structure Types',...
    'BackgroundColor',[0.3 0.5 0.7],...
    'Position',[0.1 .45 .8 .45],...
    'Visible','off');
         ExpSetup(3) = uicontrol(ExpSetup(2),'Style','togglebutton',...
             'String','1 DOF',...
             'Units','normalized',...
             'Position',[0.025 0.15 0.3 0.7]);
         ExpSetup(4) = uicontrol(ExpSetup(2),'Style','togglebutton',...
             'String','2 DOF A',...
             'Units','normalized',...
             'Position',[0.35 0.15 0.3 0.7]);
         ExpSetup(5) = uicontrol(ExpSetup(2),'Style','togglebutton',...
             'String','2 DOF B',...
             'Units','normalized',...
             'Position',[0.675 0.15 0.3 0.7]);
         ExpSetup(6) = uicontrol(ExpSetup(2),'Style','pushbutton',...
             'Units','normalized',...
             'String','!',...
             'Position',[0.875 0.15 0.1 0.15],...
             'Callback','ExpSetup(''extra options'')');
         set(ExpSetup(2),'SelectionChangeFcn','ExpSetup(''choose DOF'')');
         set(ExpSetup(2),'SelectedObject',[]);
                     
                     
                     
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%         
%Create Experimental Control Page%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Title       
ExpControl(1) = uicontrol(ph_Main,'Style','text',...
    'String','Experimental Control',...
    'FontSize',20,...
    'ForegroundColor',[1 1 1],...
    'BackgroundColor',[0.3 0.5 0.7],...
    'Units','normalized',...
    'Position',[0.3 0.92 0.4 0.04],...
    'Visible','off');

%Tab Buttons       
ExpControl(2) = uicontrol(ph_Main,'Style','togglebutton',...
    'String','Control Point',...
    'Units','normalized',...
    'Value',0,...
    'Position',[0.15 0.8 0.1 0.05],...
    'Visible','off',...
    'Callback','ExpControl(''tab toggle'')');
ExpControl(3) = uicontrol(ph_Main,'Style','togglebutton',...
    'String','Simulation',...
    'Units','normalized',...
    'Value',1,...
    'Position',[0.25 0.8 0.1 0.05],...
    'Visible','off',...
    'Callback','ExpControl(''tab toggle'')');
ExpControl(4) = uicontrol(ph_Main,'Style','togglebutton',...
    'String','Real Controller',...
    'Units','normalized',...
    'Position',[0.35 0.8 0.1 0.05],...
    'Visible','off',...
    'Callback','ExpControl(''tab toggle'')');                    

%Experimental Control Option Panels
%Simulation Panel
ExpControl(5) = uipanel('Parent',ph_Main,...
    'Visible','off',...
    'Position',[0.15 0.3 0.7 0.5]);
         ExpControl(6) = uicontrol(ExpControl(5),'Style','popupmenu',...
             'String',{'Choose DOF...','DOF 1','DOF 2'},...
             'Value',1,...
             'FontSize',10,...
             'Units','normalized',...
             'BackgroundColor',[1 1 1],...
             'Position',[0.05 0.77 0.2 0.15],...
             'Callback','ExpControl(''CtrlDOF'')');
         ExpControl(7) = uipanel('Parent',ExpControl(5),...
             'Visible','off',...
             'Position',[0.05 0.5 0.9 0.3]);
                uicontrol(ExpControl(7),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Define Control',...
                    'Position',[0.01 0.65 0.25 0.2]);
                ExpControl(8) = uicontrol(ExpControl(7),'Style','popupmenu',...
                    'String',{'Control Types...','SimUniaxialMaterial'},...
                    'Value',1,...
                    'FontSize',10,...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.7 0.4 0.2],...
                    'Callback','ExpControl(''Sim control'')');
                uicontrol(ExpControl(7),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Number of Actuators',...
                    'Position',[0.01 0.35 0.25 0.2]);
                ExpControl(9) = uicontrol(ExpControl(7),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.40 0.4 0.2],...
                    'Callback','ExpControl(''NumAct'')');
                uicontrol(ExpControl(7),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Choose Material',...
                    'Position',[0.01 0.05 0.25 0.2]);
                ExpControl(10) = uicontrol(ExpControl(7),'Style','popupmenu',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'String',{'Material Type...','Elastic','Elastic-Perfectly Plastic','Steel - Bilinear','Steel - Giuffré-Menegotto-Pinto'},...
                    'Position',[0.31 0.1 0.4 0.2],...
                    'Callback','ExpControl(''Sim Material'')');
                
         %Simulation Material Types
         %Elastic Panel
         ExpControl(11) = uipanel('Parent',ExpControl(5),...
             'Visible','off',...
             'Position',[0.05 0.35 0.9 0.15]);
                uicontrol(ExpControl(11),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Elastic Modulus (E)',...
                    'Position',[0 0.15 0.25 0.45]);
                ExpControl(12) = uicontrol(ExpControl(11),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.3 0.4 0.4],...
                    'Callback','ExpControl(''E'')');
         %EPP Panel
         ExpControl(13) = uipanel('Parent',ExpControl(5),...
             'Visible','off',...
             'Position',[0.05 0.29 0.9 0.21]);
                uicontrol(ExpControl(13),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Elastic Modulus (E)',...
                    'Position',[0 0.48 0.25 0.3]);
                ExpControl(14) = uicontrol(ExpControl(13),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.58 0.4 0.25],...
                    'Callback','ExpControl(''E'')');
                uicontrol(ExpControl(13),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Plastic Strain Point (epsP)',...
                    'Position',[0 0.03 0.25 0.3]);
                ExpControl(15) = uicontrol(ExpControl(13),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.13 0.4 0.25],...
                    'Callback','ExpControl(''epsP'')');
         %Steel Bilinear Panel
         ExpControl(16) = uipanel('Parent',ExpControl(5),...
             'Visible','off',...
             'Position',[0.05 0.2 0.9 0.3]);
                uicontrol(ExpControl(16),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Yield Strength (Fy)',...
                    'Position',[0 0.6 0.25 0.25]);
                ExpControl(17) = uicontrol(ExpControl(16),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.7 0.4 0.2],...
                    'Callback','ExpControl(''Fy'')');
                uicontrol(ExpControl(16),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Initial Elastic Modulus (E0)',...
                    'Position',[0 0.3 0.25 0.25]);
                ExpControl(18) = uicontrol(ExpControl(16),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.4 0.4 0.2],...
                    'Callback','ExpControl(''E0'')');
                uicontrol(ExpControl(16),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Strain Hardening Ratio (b)',...
                    'Position',[0 0 0.25 0.25]);
                ExpControl(19) = uicontrol(ExpControl(16),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.1 0.4 0.2],...
                    'Callback','ExpControl(''b'')');
         %Steel GMP Panel
         ExpControl(20) = uipanel('Parent',ExpControl(5),...
             'Visible','off',...
             'Position',[0.05 0.05 0.9 0.45]);
                uicontrol(ExpControl(20),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Yield Strength (Fy)',...
                    'Position',[0 0.77 0.25 0.15]);
                ExpControl(21) = uicontrol(ExpControl(20),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.82 0.4 0.13],...
                    'Callback','ExpControl(''Fy'')');
                uicontrol(ExpControl(20),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Initial Elastic Modulus (E)',...
                    'Position',[0 0.54 0.25 0.15]);
                ExpControl(22) = uicontrol(ExpControl(20),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.58 0.4 0.13],...
                    'Callback','ExpControl(''E'')');
                uicontrol(ExpControl(20),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Strain Hardening Ratio (b)',...
                    'Position',[0 0.31 0.25 0.15]);
                ExpControl(23) = uicontrol(ExpControl(20),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.35 0.4 0.13],...
                    'Callback','ExpControl(''b'')');
                uicontrol(ExpControl(20),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Elastic-Plastic Transition (R0)',...
                    'Position',[0 0.08 0.25 0.15]);
                ExpControl(24) = uicontrol(ExpControl(20),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.11 0.4 0.13],...
                    'Callback','ExpControl(''R0'')');
                GMP_help = uicontrol(ExpControl(20),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','?',...
                    'ToolTipString',sprintf('The variable R0 controls the elastic-plastic transition\nRecommended values range between 10 and 20'),...
                    'Position',[0.75 0.11 0.05 0.1]);
                
%Real Controller Panel
ExpControl(25) = uipanel('Parent',ph_Main,...
    'Visible','off',...
    'Position',[0.15 0.3 0.7 0.5]);
         ExpControl(26) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Position',[0.05 0.65 0.9 0.15]);
                uicontrol(ExpControl(26),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Define Control',...
                    'Position',[0 0.15 0.25 0.45]);
                ExpControl(27) = uicontrol(ExpControl(26),'Style','popupmenu',...
                    'String',{'Control Types...','LabVIEW','MTSCsi','SCRAMNet','dSpace','xPCtarget'},...
                    'Value',1,...
                    'FontSize',10,...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.3 0.4 0.4],...
                    'Callback','ExpControl(''Real control'')'); 
         %LabVIEW Panels
         ExpControl(28) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Tag','LabVIEW1',...
             'Position',[0.05 0.45 0.9 0.2]);
                uicontrol(ExpControl(28),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','LabVIEW IP Address',...
                    'Position',[0 0.48 0.25 0.3]);
                ExpControl(29) = uicontrol(ExpControl(28),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.58 0.4 0.25],...
                    'Callback','ExpControl(''ipAddr'')');
                uicontrol(ExpControl(28),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','LabVIEW IP Port',...
                    'Position',[0 0.03 0.25 0.3]);
                ExpControl(30) = uicontrol(ExpControl(28),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.13 0.4 0.25],...
                    'Callback','ExpControl(''ipPort'')');
         ExpControl(31) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Tag','LabVIEW2',...
             'Position',[0.05 0.25 0.9 0.2]);
                uicontrol(ExpControl(31),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Trial CP(s)',...
                    'Position',[0 0.48 0.25 0.3]);
                ExpControl(32) = uicontrol(ExpControl(31),'Style','listbox',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'String','',...
                    'Position',[0.31 0.58 0.4 0.25],...
                    'Callback','ExpControl(''TrialCP'')');
                uicontrol(ExpControl(31),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Output CP(s)',...
                    'Position',[0 0.03 0.25 0.3]);
                ExpControl(33) = uicontrol(ExpControl(31),'Style','listbox',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'String','',...
                    'Position',[0.31 0.13 0.4 0.25],...
                    'Callback','ExpControl(''OutputCP'')');
         %MTSCsi Panels
         ExpControl(34) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Tag','MTSCsi1',...
             'Position',[0.05 0.45 0.9 0.2]);
                uicontrol(ExpControl(34),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Configuration File Name',...
                    'Position',[0 0.48 0.25 0.3]);
                ExpControl(35) = uicontrol(ExpControl(34),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.58 0.4 0.25],...
                    'Callback','ExpControl(''ConfigName'')');
                ConfigBrowse = uicontrol(ExpControl(34),'Style','pushbutton',...
                    'Units','normalized',...
                    'String','...',...
                    'Tag','ConfigBrowse',...
                    'Position',[0.74 0.58 0.08 0.25],...
                    'Callback','ExpControl(''loadConfig'')');
                uicontrol(ExpControl(34),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Configuration File Path',...
                    'Position',[0 0.03 0.25 0.3]);
                ExpControl(36) = uicontrol(ExpControl(34),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.13 0.4 0.25],...
                    'Callback','ExpControl(''ConfigPath'')');
         ExpControl(37) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Tag','MTSCsi2',...
             'Position',[0.05 0.3 0.9 0.15]);
                uicontrol(ExpControl(37),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Ramp Time',...
                    'Position',[0 0.35 0.25 0.3]);
                ExpControl(38) = uicontrol(ExpControl(37),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.3 0.4 0.4],...
                    'Callback','ExpControl(''rampTime'')');
         %SCRAMNet Panel
         ExpControl(39) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Tag','SCRAMNet',...
             'Position',[0.05 0.45 0.9 0.2]);
                uicontrol(ExpControl(39),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Memory Offset (bytes)',...
                    'Position',[0 0.48 0.25 0.3]);
                ExpControl(40) = uicontrol(ExpControl(39),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.58 0.4 0.25],...
                    'Callback','ExpControl(''memOffset'')');
                uicontrol(ExpControl(39),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Number of Actuator Channels',...
                    'Position',[0 0.05 0.25 0.3]);
                ExpControl(41) = uicontrol(ExpControl(39),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.13 0.4 0.25],...
                    'Callback','ExpControl(''NumActCh'')');
         %dSpace Panel
         ExpControl(42) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Tag','dSpace',...
             'Position',[0.05 0.45 0.9 0.2]);
                uicontrol(ExpControl(42),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Predictor-Corrector Type',...
                    'Position',[0 0.45 0.25 0.35]);
                ExpControl(43) = uicontrol(ExpControl(42),'Style','popupmenu',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'String',{'Choose Type...','Displacement','Displacement and Velocity','Displacement, Velocity and Acceleration'},...
                    'Position',[0.31 0.58 0.4 0.25],...
                    'Callback','ExpControl(''PCtype'')');
                uicontrol(ExpControl(42),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Board Name',...
                    'Position',[0 0.03 0.25 0.3]);
                ExpControl(44) = uicontrol(ExpControl(42),'Style','popupmenu',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'String',{'Choose Board Name...','DS1103','DS1104'},...
                    'Position',[0.31 0.13 0.4 0.25],...
                    'Callback','ExpControl(''boardName'')');
         %xPCtarget Panels
         ExpControl(45) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Tag','xPCtarget1',...
             'Position',[0.05 0.5 0.9 0.15]);
                uicontrol(ExpControl(45),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Predictor-Corrector Type',...
                    'Position',[0 0.15 0.25 0.45]);
                ExpControl(46) = uicontrol(ExpControl(45),'Style','popupmenu',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'String',{'Choose Type...','Displacement','Displacement and Velocity','Displacement, Velocity and Acceleration'},...
                    'Position',[0.31 0.3 0.4 0.4],...
                    'Callback','ExpControl(''PCtype'')');
         ExpControl(47) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Tag','xPCtarget2',...
             'Position',[0.05 0.3 0.9 0.2]);
                uicontrol(ExpControl(47),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','xPC Target IP Address',...
                    'Position',[0 0.48 0.25 0.3]);
                ExpControl(48) = uicontrol(ExpControl(47),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.58 0.4 0.25],...
                    'Callback','ExpControl(''ipAddr'')');
                uicontrol(ExpControl(47),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','xPC Target IP Port',...
                    'Position',[0 0.03 0.25 0.3]);
                ExpControl(49) = uicontrol(ExpControl(47),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','22222',...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.13 0.4 0.25],...
                    'Callback','ExpControl(''ipPort'')');
         ExpControl(50) = uipanel('Parent',ExpControl(25),...
             'Visible','off',...
             'Tag','xPCtarget3',...
             'Position',[0.05 0.1 0.9 0.2]);
                uicontrol(ExpControl(50),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Application Name',...
                    'Position',[0 0.48 0.25 0.3]);
                ExpControl(51) = uicontrol(ExpControl(50),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.58 0.4 0.25],...
                    'Callback','ExpControl(''appName'')');
                AppBrowse = uicontrol(ExpControl(50),'Style','pushbutton',...
                    'Units','normalized',...
                    'String','...',...
                    'Tag','AppBrowse',...
                    'Position',[0.74 0.58 0.08 0.25],...
                    'Callback','ExpControl(''loadApp'')');
                uicontrol(ExpControl(50),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Application Path',...
                    'Position',[0 0.03 0.25 0.3]);
                ExpControl(52) = uicontrol(ExpControl(50),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.13 0.4 0.25],...
                    'Callback','ExpControl(''appPath'')');

%Control Points Panel
ExpControl(53) = uipanel('Parent',ph_Main,...
    'Visible','off',...
    'Position',[0.15 0.3 0.7 0.5]);
         ExpControl(54) = uicontrol(ExpControl(53),'Style','popupmenu',...
             'String',{'Existing Control Points...','Control Point 1','Control Point 2'},...
             'Value',1,...
             'FontSize',10,...
             'Units','normalized',...
             'BackgroundColor',[1 1 1],...
             'Position',[0.05 0.77 0.2 0.15],...
             'Callback','ExpControl(''SwitchCP'')');
         ExpControl(55) = uipanel('Parent',ExpControl(53),...
             'Visible','off',...
             'Tag','CP1',...
             'Position',[0.05 0.5 0.9 0.3]);
                uicontrol(ExpControl(55),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Name',...
                    'Position',[0.01 0.65 0.25 0.2]);
                ExpControl(56) = uicontrol(ExpControl(55),'Style','edit',...
                    'FontSize',10,...
                    'Units','normalized',...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.7 0.4 0.2]);
                uicontrol(ExpControl(55),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Node Number',...
                    'Position',[0.01 0.35 0.25 0.2]);
                ExpControl(57) = uicontrol(ExpControl(55),'Style','edit',...
                    'String','1',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.40 0.4 0.2],...
                    'Callback','ExpControl(''nodeNum'')');
                uicontrol(ExpControl(55),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Number of Response Quantities',...
                    'Position',[0.01 0.05 0.25 0.2]);
                ExpControl(58) = uicontrol(ExpControl(55),'Style','edit',...
                    'Units','normalized',...
                    'String','1',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.1 0.4 0.2],...
                    'Callback','ExpControl(''RQNum'')');
                
         %Control Point Options
         ExpControl(59) = uipanel('Parent',ExpControl(53),...
             'Visible','off',...
             'Tag','CP2',...
             'Position',[0.05 0.07 0.9 0.43]);
                uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Direction',...
                    'Position',[0.31 0.77 0.1 0.15]);
                uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Response',...
                    'Position',[0.43 0.77 0.1 0.15]);
                uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Factor',...
                    'Position',[0.55 0.77 0.1 0.15]);
                uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String',sprintf('Assign\nLimits?'),...
                    'Position',[0.67 0.78 0.1 0.2]);
                uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String',sprintf('Lower\nLimit'),...
                    'Position',[0.76 0.78 0.1 0.2]);
                uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String',sprintf('Upper\nLimit'),...
                    'Position',[0.88 0.78 0.1 0.2]);
                %Divide Frame
                Height = 0.005;
                uicontrol(ExpControl(59),'Style','frame', ...
                    'Units','normalized', ...
                    'BackgroundColor',[0 0 0],...
                    'ForegroundColor',[0 0 0],...
                    'Position',[0.31 0.79 0.68 Height]);
                uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','Define Control Point',...
                    'Position',[0 0.56 0.25 0.15]);
                ExpControl(60) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Direction...','UX','UY','UZ','RX','RY','RZ'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.31 0.56 0.1 0.15]);
                ExpControl(61) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Response...','disp','vel','accel','force','time'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.43 0.56 0.1 0.15]);
                ExpControl(62) = uicontrol(ExpControl(59),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','1',...
                    'BackgroundColor',[1 1 1],...
                    'Position',[0.56 0.59 0.08 0.1]);
                ExpControl(63) = uicontrol(ExpControl(59),'Style','checkbox',...
                    'Units','normalized',...
                    'String','',...
                    'Tag','Line1',...
                    'Position',[0.71 0.59 0.2 0.1],...
                    'Callback','ExpControl(''assign limits'')');
                ExpControl(64) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Position',[0.77 0.59 0.08 0.1]);
                ExpControl(65) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Position',[0.89 0.59 0.08 0.1]);
                
                ExpControl(66) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Direction...','UX','UY','UZ','RX','RY','RZ'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.31 0.39 0.1 0.15]);
                ExpControl(67) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Response...','disp','vel','accel','force','time'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.43 0.39 0.1 0.15]);
                ExpControl(68) = uicontrol(ExpControl(59),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','1',...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.56 0.42 0.08 0.1]);
                ExpControl(69) = uicontrol(ExpControl(59),'Style','checkbox',...
                    'Units','normalized',...
                    'String','',...
                    'Tag','Line2',...
                    'Position',[0.71 0.42 0.2 0.1],...
                    'Visible','off',...
                    'Callback','ExpControl(''assign limits'')');
                ExpControl(70) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.77 0.42 0.08 0.1]);
                ExpControl(71) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.89 0.42 0.08 0.1]);
                
                ExpControl(72) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Direction...','UX','UY','UZ','RX','RY','RZ'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.31 0.22 0.1 0.15]);
                ExpControl(73) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Response...','disp','vel','accel','force','time'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.43 0.22 0.1 0.15]);
                ExpControl(74) = uicontrol(ExpControl(59),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','1',...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.56 0.25 0.08 0.1]);
                ExpControl(75) = uicontrol(ExpControl(59),'Style','checkbox',...
                    'Units','normalized',...
                    'String','',...
                    'Tag','Line3',...
                    'Position',[0.71 0.25 0.2 0.1],...
                    'Visible','off',...
                    'Callback','ExpControl(''assign limits'')');
                ExpControl(76) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.77 0.25 0.08 0.1]);
                ExpControl(77) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.89 0.25 0.08 0.1]);
                
                ExpControl(78) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Direction...','UX','UY','UZ','RX','RY','RZ'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.31 0.05 0.1 0.15]);
                ExpControl(79) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Response...','disp','vel','accel','force','time'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.43 0.05 0.1 0.15]);
                ExpControl(80) = uicontrol(ExpControl(59),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','1',...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.56 0.08 0.08 0.1]);
                ExpControl(81) = uicontrol(ExpControl(59),'Style','checkbox',...
                    'Units','normalized',...
                    'String','',...
                    'Tag','Line4',...
                    'Position',[0.71 0.08 0.2 0.1],...
                    'Visible','off',...
                    'Callback','ExpControl(''assign limits'')');
                ExpControl(82) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.77 0.08 0.08 0.1]);
                ExpControl(83) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.89 0.08 0.08 0.1]);
                
                ExpControl(84) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Direction...','UX','UY','UZ','RX','RY','RZ'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.31 0.05 0.1 0.15]);
                ExpControl(85) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Response...','disp','vel','accel','force','time'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.43 0.05 0.1 0.15]);
                ExpControl(86) = uicontrol(ExpControl(59),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','1',...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.56 0.08 0.08 0.1]);
                ExpControl(87) = uicontrol(ExpControl(59),'Style','checkbox',...
                    'Units','normalized',...
                    'String','',...
                    'Tag','Line5',...
                    'Position',[0.71 0.08 0.2 0.1],...
                    'Visible','off',...
                    'Callback','ExpControl(''assign limits'')');
                ExpControl(88) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.77 0.08 0.08 0.1]);
                ExpControl(89) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.89 0.08 0.08 0.1]);
                
                ExpControl(90) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Direction...','UX','UY','UZ','RX','RY','RZ'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.31 0.05 0.1 0.15]);
                ExpControl(91) = uicontrol(ExpControl(59),'Style','popupmenu',...
                    'String',{'Response...','disp','vel','accel','force','time'},...
                    'Value',1,...
                    'Units','normalized',...
                    'FontSize',10,...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.43 0.05 0.1 0.15]);
                ExpControl(92) = uicontrol(ExpControl(59),'Style','edit',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','1',...
                    'BackgroundColor',[1 1 1],...
                    'Visible','off',...
                    'Position',[0.56 0.08 0.08 0.1]);
                ExpControl(93) = uicontrol(ExpControl(59),'Style','checkbox',...
                    'Units','normalized',...
                    'String','',...
                    'Tag','Line6',...
                    'Position',[0.71 0.08 0.2 0.1],...
                    'Visible','off',...
                    'Callback','ExpControl(''assign limits'')');
                ExpControl(94) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.77 0.08 0.08 0.1]);
                ExpControl(95) = uicontrol(ExpControl(59),'Style','text',...
                    'Units','normalized',...
                    'FontSize',10,...
                    'String','',...
                    'BackgroundColor','default',...
                    'Visible','off',...
                    'Position',[0.89 0.08 0.08 0.1]);
                
         ExpControl(96) = uicontrol('Parent', ExpControl(53),...
             'Style','pushbutton',...
             'String','Save Control Point',...
             'Units','normalized',...
             'FontSize',10,...
             'Position',[0.8 0.01 0.15 0.06],...
             'Visible','off',...
             'Callback','ExpControl(''saveCP'')');



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%         
%Create Analysis Page%
%%%%%%%%%%%%%%%%%%%%%%

%Title       
Analysis(1) = uicontrol(ph_Main,'Style','text',...
    'String','Analysis',...
    'FontSize',20,...
    'Units','normalized',...
    'ForegroundColor',[1 1 1],...
    'BackgroundColor',panel_color,...
    'Position',[0.3 0.92 0.4 0.04],...
    'Visible','off');

%Create Panel
Analysis(2) = uipanel('Parent',ph_Main,...
    'Position',[0.25 0.65 0.5 0.2],...
    'Tag','Direction 2',...
    'Visible','off');
        uicontrol(Analysis(2),'Style','text',...
            'Units','normalized',...
            'FontSize',10,...
            'String','dt: ',...
            'Position',[0.1 0.66 0.05 0.1]);
        Analysis(3) = uicontrol(Analysis(2),'Style','edit',...
            'Units','normalized',...
            'BackgroundColor',[1 1 1],...
            'FontSize',10,...
            'String','No dt defined!',...
            'Position',[0.18 0.65 0.32 0.15],...
            'Callback','Analysis(''dtAnalysis'')');
        Analysis(4) = uicontrol(Analysis(2),'Style','text',...
            'Units','normalized',...
            'String','<          ...',...
            'FontSize',10,...
            'Position',[0.52 0.66 0.25 0.1]);
        Analysis(12) = uicontrol(Analysis(2),'Style','pushbutton',...
             'String','Write TCL File',...
             'Units','normalized',...
             'FontSize',10,...
             'Position',[0.3 0.33 0.4 0.2],...
             'Callback','WriteTCL');
        Analysis(5) = uicontrol(Analysis(2),'Style','pushbutton',...
             'String','Generate Report',...
             'Units','normalized',...
             'FontSize',10,...
             'Position',[0.3 0.05 0.4 0.2],...
             'Callback','Analysis(''generate report'')');

%Analysis Button Group    
Analysis(6) = uibuttongroup('Parent',ph_Main,...
    'BackgroundColor',[0.3 0.5 0.7],...
    'Position',[0.25 .25 .5 .3],...
    'Visible','off');
         Analysis(7) = uicontrol(Analysis(6),'Style','togglebutton',...
             'String','Start',...
             'BackgroundColor',[0 0.6 0],...
             'Units','normalized',...
             'Position',[0.025 0.15 0.3 0.7]);
         Analysis(8) = uicontrol(Analysis(6),'Style','togglebutton',...
             'String','Pause',...
             'BackgroundColor',[1 1 0],...
             'Units','normalized',...
             'Position',[0.35 0.15 0.3 0.7]);
         Analysis(9) = uicontrol(Analysis(6),'Style','togglebutton',...
             'String','Stop',...
             'BackgroundColor',[0.8 0 0],...
             'Units','normalized',...
             'Position',[0.675 0.15 0.3 0.7]);
         %Remember to remove string
         set(Analysis(6),'SelectionChangeFcn','Analysis(''choose option'')');
         set(Analysis(6),'SelectedObject',[]);
         
Analysis(10) = uicontrol('Parent', ph_Main,...
    'Style','pushbutton',...
    'String','Run New Test',...
    'Units','normalized',...
    'FontSize',10,...
    'Position',[0.8 0.15 0.1 0.04],...
    'Visible','off',...
    'Callback','Analysis(''new test'')');         
Analysis(11) = uicontrol('Parent', ph_Main,...
    'Style','pushbutton',...
    'String','Quit',...
    'Units','normalized',...
    'FontSize',10,...
    'Position',[0.8 0.1 0.1 0.04],...
    'Visible','off',...
    'Callback',@Quit_Program);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Display the GUI
set(f, 'Visible','on');

%%%%%%%%%%%%%%%
% Save handles%
%%%%%%%%%%%%%%%

%Create the structure of handles
handles = guidata(gcf);
handles.Menu = Menu;
handles.Sidebar = Sidebar;
handles.Structure = Struct;
handles.GroundMotions = GM;
handles.ES = ExpSetup;
handles.EC = ExpControl;
handles.Analysis = Analysis;

%%%%%%%%%%%%%%%%%%%
%Initialize Fields%
%%%%%%%%%%%%%%%%%%%

%Initialize Model Parameters
handles.Model.M = [];
handles.Model.K = [];
handles.Model.StopFlag = 0;
handles.Model.firstStart = 1;
handles.Model.Zeta = [];
%Initialize Ground Motion Data
handles.GM.AmpFact(1) = str2num(get(handles.GroundMotions(4),'String'));
handles.GM.TimeFact(1) = str2num(get(handles.GroundMotions(5),'String'));
handles.GM.dt = 0;
handles.GM.t = {0};
handles.GM.ag = {0};
handles.GM.scaledt = 0;
handles.GM.scalet = {0};
handles.GM.scaleag = {0};
handles.GM.Spectra = {0};
%Initialize Experimental Controls
handles.ExpControl.Type = 'Simulation';
handles.ExpControl.DOF1.SimMaterial = [];
handles.ExpControl.DOF2.SimMaterial = [];
handles.ExpControl.DOF1.E = [];
handles.ExpControl.DOF2.E = [];
handles.ExpControl.DOF1.epsP = [];
handles.ExpControl.DOF2.epsP = [];
handles.ExpControl.DOF1.Fy = [];
handles.ExpControl.DOF2.Fy = [];
handles.ExpControl.DOF1.E0 = [];
handles.ExpControl.DOF2.E0 = [];
handles.ExpControl.DOF1.b = [];
handles.ExpControl.DOF2.b = [];
handles.ExpControl.DOF1.R0 = [];
handles.ExpControl.DOF2.R0 = [];
handles.ExpControl.RealControl.ipAddr = [];
handles.ExpControl.RealControl.ipPort = 22222;
handles.ExpControl.RealControl.TrialCP = [];
handles.ExpControl.RealControl.OutputCP = [];
handles.ExpControl.RealControl.ConfigName = [];
handles.ExpControl.RealControl.ConfigPath = [];
handles.ExpControl.RealControl.rampTime = [];
handles.ExpControl.RealControl.memOffset = [];
handles.ExpControl.RealControl.NumActCh = [];
handles.ExpControl.RealControl.PCvalue = 1;
handles.ExpControl.RealControl.boardName = [];
handles.ExpControl.RealControl.appName = [];
handles.ExpControl.RealControl.appPath = [];
handles.ExpControl.RealControl.SimMaterial = [];
handles.ExpControl.store.SimActive = 6;
handles.ExpControl.store.RealActive = (26:27);
handles.ExpControl.store.CPActive = (60:65);
handles.ExpControl.store.RQ = 1;
handles.ExpControl.store.DOFOptions = get(handles.EC(6),'String');
handles.ExpControl.store.MatOptions = get(handles.EC(10),'String');
handles.ExpControl.store.CPOptions = get(handles.EC(54),'String');
handles.ExpControl.store.NodeOptions = get(handles.EC(57),'String');
handles.ExpControl.store.DirOptions = get(handles.EC(60),'String');
handles.ExpControl.store.RespOptions = get(handles.EC(61),'String');

%Store directory
handles.Model.DIR = pwd;


%Save the structure of handles
guidata(gcf,handles);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Callback for main template tabs
    function template_toggle_Callback(source, eventdata)
        handles = guidata(gcf);
        Page_selection = get(get(source,'SelectedObject'),'String');
        switch Page_selection;
            case 'Structure'
                set(handles.Structure,'Visible','on');
                set(handles.GroundMotions,'Visible','off');
                set(get(handles.GroundMotions(7), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(8), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(9), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(15), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(16), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(17), 'Children'), 'Visible', 'off');
                set(handles.ES,'Visible','off');
                set(handles.EC,'Visible','off');
                set(handles.Analysis,'Visible','off');
                
            case 'Ground Motions'
                set(handles.Structure,'Visible','off');
                set(handles.ES,'Visible','off');
                set(handles.EC,'Visible','off');
                set(handles.Analysis,'Visible','off');
                set(get(handles.GroundMotions(7), 'Children'), 'Visible', 'on');
                set(get(handles.GroundMotions(8), 'Children'), 'Visible', 'on');
                set(get(handles.GroundMotions(9), 'Children'), 'Visible', 'on');
                set(get(handles.GroundMotions(15), 'Children'), 'Visible', 'on');
                set(get(handles.GroundMotions(16), 'Children'), 'Visible', 'on');
                set(get(handles.GroundMotions(17), 'Children'), 'Visible', 'on');
                if ~isfield(handles.Model, 'Type')
                    msgbox('Must select structure type first!','Error','error');
                    %Return to structure page if no structure chosen
                    set(tbh1, 'Value', 1)
                    set(handles.Structure,'Visible','on');
                    set(handles.GroundMotions,'Visible','off');
                    set(get(handles.GroundMotions(7), 'Children'), 'Visible', 'off');
                    set(get(handles.GroundMotions(8), 'Children'), 'Visible', 'off');
                    set(get(handles.GroundMotions(9), 'Children'), 'Visible', 'off');
                    set(get(handles.GroundMotions(15), 'Children'), 'Visible', 'off');
                    set(get(handles.GroundMotions(16), 'Children'), 'Visible', 'off');
                    set(get(handles.GroundMotions(17), 'Children'), 'Visible', 'off');
                elseif strcmp(handles.Model.Type, '2 DOF B') ~= 1
                    %Hide plots for DOF 2 if 1 DOF or 2 DOF A is chosen
                    set(handles.GroundMotions(1:9),'Visible','on');
                    set(handles.GroundMotions(2),'Position',[0.3 0.65 0.4 0.25]);
                    set(handles.GroundMotions(7),'Position',[0.2 0.45 0.6 0.15]);
                    set(handles.GroundMotions(8),'Position',[0.2 0.25 0.6 0.15]);
                    set(handles.GroundMotions(9),'Position',[0.2 0.08 0.6 0.15]);
                    set(handles.GroundMotions(10:17),'Visible','off')
                else
                    set(handles.GroundMotions,'Visible','on');
                    set(handles.GroundMotions(2),'Position',[0.2 0.65 0.25 0.25]);
                    set(handles.GroundMotions(7),'Position',[0.15 0.45 0.35 0.15]);
                    set(handles.GroundMotions(8),'Position',[0.15 0.25 0.35 0.15]);
                    set(handles.GroundMotions(9),'Position',[0.15 0.08 0.35 0.15]);
                end
                %Update spectral response quantity plots if zeta has been
                %changed
                if isfield(handles.GM.Spectra{1},'psdAcc')
                    [rows cols] = size(get(handles.GroundMotions(8),'Children'));
                    if rows ~= length(handles.Model.Zeta)
                        m = 1.0;
                        minT = 0.01;
                        maxT = 4.99;
                        numTvalues = 300;
                        handles.GM.Spectra{1} = ResponseSpectraElastic(handles.GM.scaleag{1},handles.GM.scaledt(1),m,handles.Model.Zeta,minT,maxT,numTvalues);
                        plot(handles.GroundMotions(8), handles.GM.Spectra{1}.T, handles.GM.Spectra{1}.psdAcc);
                        plot(handles.GroundMotions(9), handles.GM.Spectra{1}.T, handles.GM.Spectra{1}.dsp);
                        if strcmp(handles.Model.Type, '2 DOF B')
                            if length(handles.GM.Spectra) == 2
                                handles.GM.Spectra{2} = ResponseSpectraElastic(handles.GM.scaleag{2},handles.GM.scaledt(2),m,handles.Model.Zeta,minT,maxT,numTvalues);
                                plot(handles.GroundMotions(16), handles.GM.Spectra{2}.T, handles.GM.Spectra{2}.psdAcc);
                                plot(handles.GroundMotions(17), handles.GM.Spectra{2}.T, handles.GM.Spectra{2}.dsp);
                            end
                        end
                    end
                end
                
            case 'Experimental Setup'
                set(handles.Structure,'Visible','off');
                set(handles.GroundMotions,'Visible','off');
                set(get(handles.GroundMotions(7), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(8), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(9), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(15), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(16), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(17), 'Children'), 'Visible', 'off');
                set(handles.ES,'Visible','on');
                set(handles.EC,'Visible','off');
                set(handles.Analysis,'Visible','off');
                
            case 'Experimental Control'
                set(handles.Structure,'Visible','off');
                set(handles.GroundMotions,'Visible','off');
                set(get(handles.GroundMotions(7), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(8), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(9), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(15), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(16), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(17), 'Children'), 'Visible', 'off');
                set(handles.ES,'Visible','off');
                set(handles.Analysis,'Visible','off');
                if get(handles.EC(2),'Value') == 1
                    set(handles.EC([1:4 53:59 96]),'Visible','on'); 
                    set(handles.EC(handles.ExpControl.store.CPActive),'Visible','on');
                elseif get(handles.EC(3),'Value') == 1
                    set(handles.EC(1:6),'Visible','on');
                    set(handles.EC(handles.ExpControl.store.SimActive),'Visible','on');
                elseif get(handles.EC(4),'Value') == 1
                    set(handles.EC([1:4 25:27]),'Visible','on');
                    set(handles.EC(28:52),'Visible','off');
                    set(handles.EC(handles.ExpControl.store.RealActive),'Visible','on');
                else
                    switch handles.ExpControl.Type
                        case 'Simulation'
                            set(handles.EC(3),'Value',1);
                            set(handles.EC(1:6),'Visible','on');
                            set(handles.EC(handles.ExpControl.store.SimActive),'Visible','on');
                        case 'Real'
                            set(handles.EC(4),'Value',1);
                            set(handles.EC([1:4 25:27]),'Visible','on');
                            set(handles.EC(28:52),'Visible','off');
                            set(handles.EC(handles.ExpControl.store.RealActive),'Visible','on');
                    end
                end
                    
            case 'Analysis'
                set(handles.Structure,'Visible','off');
                set(handles.GroundMotions,'Visible','off');
                set(get(handles.GroundMotions(7), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(8), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(9), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(15), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(16), 'Children'), 'Visible', 'off');
                set(get(handles.GroundMotions(17), 'Children'), 'Visible', 'off');
                set(handles.ES,'Visible','off');
                set(handles.EC,'Visible','off');
                set(handles.Analysis,'Visible','on');
                %Calculate maximum allowable time step
                %For now we introduce a check of whether the field minT exists to avoid
                %errors. This should be REMOVED/MODIFIED
                if isfield(handles.Model, 'minTDOF');
                    handles.Model.Maxdt = 2/handles.Model.Omega(handles.Model.minTDOF);
                    dt_str = {'<    ' num2str(handles.Model.Maxdt)};
                    set(handles.Analysis(4),'String',[dt_str{1} dt_str{2}]);
                    if handles.GM.dtAnalysis > handles.Model.Maxdt
                        msgbox(['Time step too large! Must be less than ' num2str(handles.Model.Maxdt)], 'Time Step Error', 'warn');
                    end
                    guidata(gcbf, handles);
                end
        end
    end

%Callback for program quit
    function Quit_Program(source, eventdata)
        close_program = questdlg('Are you sure you want to quit?','Quit?','Yes','Cancel','Yes');
        switch close_program
            case 'Yes'
                delete(gcf);
                close all;
            case 'Cancel'
                quit cancel;
        end
    end

end