function GUI_ErrorMonitors(varargin)
%GUI_ERRORMONITORS to define the layout of the error monitors page
% GUI_ErrorMonitors(varargin)
%
% varargin : variable length input argument list
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                          OpenFresco Express                          %%
%%    GUI for the Open Framework for Experimental Setup and Control     %%
%%                                                                      %%
%%   (C) Copyright 2011, The Pacific Earthquake Engineering Research    %%
%%            Center (PEER) & MTS Systems Corporation (MTS)             %%
%%                         All Rights Reserved.                         %%
%%                                                                      %%
%%     Commercial use of this program without express permission of     %%
%%                 PEER and MTS is strictly prohibited.                 %%
%%     See Help -> OpenFresco Express Disclaimer for information on     %%
%%   usage and redistribution, and for a DISCLAIMER OF ALL WARRANTIES.  %%
%%                                                                      %%
%%   Developed by:                                                      %%
%%     Andreas Schellenberg (andreas.schellenberg@gmail.com)            %%
%%     Carl Misra (carl.misra@gmail.com)                                %%
%%     Stephen A. Mahin (mahin@berkeley.edu)                            %%
%%                                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% $Revision$
% $Date$
% $URL$

% check if window already exists
if ~isempty(findobj('Tag','ErrMon'))
    figure(findobj('Tag','ErrMon'));
    return
end

% initialization tasks
handles = guidata(findobj('Tag','OpenFrescoExpress'));
SS = handles.Store.SS;

% find longest motion
tEnd = 0.0;
switch handles.GM.loadType
    case 'Ground Motions'
        numMotions = size(handles.Model.b,2);
        for mo=1:numMotions
            tEndi = handles.GM.scalet{mo}(end);
            if tEndi > tEnd
                tEnd = tEndi;
            end
        end
    case 'Initial Conditions'
        tEnd = handles.GM.rampTime + handles.GM.vibTime;
end

% main figure
f_ErrorMon = figure('Name','Error Monitors',...
    'Visible','on',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Tag','ErrMon',...
    'Color',[0.3 0.5 0.7],...
    'Position',[SS(3)*0.12,SS(4)*0.05,SS(3)*0.87,SS(4)*0.87]);
orient(f_ErrorMon,'landscape');
%ModifyPrintSetup(f_ErrorMon,'PrintUI',0);

% =========================================================================
% 1-DOF Case
if strcmp(handles.Model.Type,'1 DOF')
    % toolbar
    File(1) = uimenu('Position',1,'Label','File');
    uimenu(File(1),'Position',1,'Label','Save As FIG','Accelerator','M', ...
        'Callback','PrintWithHeader(''fig'',''EM1e'',[-0.06,0.32,0.03,0.32])');
    uimenu(File(1),'Position',2,'Label','Save As PDF','Accelerator','S', ...
        'Callback','PrintWithHeader(''pdf'',''EM1e'',[-0.06,0.32,0.03,0.32])');
    uimenu(File(1),'Position',3,'Label','Copy','Accelerator','C', ...
        'Callback','PrintWithHeader(''clipboard'',''EM1e'',[-0.06,0.32,0.03,0.32])');
    uimenu(File(1),'Position',4,'Label','Print','Accelerator','P', ...
        'Callback','PrintWithHeader(''printer'',''EM1e'',[-0.06,0.32,0.03,0.32])');
    Help(1) = uimenu('Position',2,'Label','Help');
    uimenu(Help(1),'Position',1,'Label','About Error Plots', ...
        'Accelerator','H','Callback','AxesHelp(''about error'')');
    uimenu('Position',3,'Label','|');
    StdMenu(1) = uimenu('Position',4,'Label','MATLAB Menu');
    uimenu(StdMenu(1),'Position',1,'Label','Turn on', ...
        'Callback','set(gcf,''MenuBar'',''figure''); set(gcf,''Toolbar'',''figure'');');
    uimenu(StdMenu(1),'Position',2,'Label','Turn off', ...
        'Callback','set(gcf,''MenuBar'',''none''); set(gcf,''Toolbar'',''none'');');
    
    % title
    uicontrol(f_ErrorMon,'Style','text',...
        'String','Error Monitors',...
        'FontSize',20,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'Units','normalized',...
        'Position',[0.3 0.87 0.4 0.1],...
        'FontName',handles.Store.font);
    
    % DOF 1 figures
    a_ErrorMonitors_eX = axes('Parent',f_ErrorMon,...
        'Tag','EM1e',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''e1'')',...
        'Position',[0.06 0.74 0.91 0.13],'Box','on',...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_eX,'Time [sec]');
    ylabel(a_ErrorMonitors_eX,'Disp Error [L]');
    a_ErrorMonitors_efX = axes('Parent',f_ErrorMon,...
        'Tag','EM1ffte',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''fft1'')',...
        'Position',[0.06 0.54 0.91 0.13],'Box','on',...
        'YScale','log');
    grid('on');
    xlabel(a_ErrorMonitors_efX,'Frequency [Hz]');
    ylabel(a_ErrorMonitors_efX,'Fourier Amp [L/sec]');
    a_ErrorMonitors_ddX = axes('Parent',f_ErrorMon,...
        'Tag','EM1MeasCmd',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''dd1'')',...
        'Position',[0.06 0.07 0.41 0.41],'Box','on');
    %axis(a_ErrorMonitors_ddX,'equal');
    grid('on');
    xlabel(a_ErrorMonitors_ddX,'Command Disp [L]');
    ylabel(a_ErrorMonitors_ddX,'Measured Disp [L]');
    a_ErrorMonitors_etX = axes('Parent',f_ErrorMon,...
        'Tag','EM1track',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''TI1'')',...
        'Position',[0.56 0.07 0.41 0.41],'Box','on',...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_etX,'Time [sec]');
    ylabel(a_ErrorMonitors_etX,'Tracking Indicator [L^2]');
    
% =========================================================================
% 2-DOF case
else
    % toolbar
    File(1) = uimenu('Position',1,'Label','File');
    uimenu(File(1),'Position',1,'Label','Save As FIG','Accelerator','M', ...
        'Callback','PrintWithHeader(''fig'',''EM1e'',[-0.13,0.32,1.2,0.32])');
    uimenu(File(1),'Position',2,'Label','Save As PDF','Accelerator','S', ...
        'Callback','PrintWithHeader(''pdf'',''EM1e'',[-0.13,0.32,1.2,0.32])');
    uimenu(File(1),'Position',3,'Label','Copy','Accelerator','C', ...
        'Callback','PrintWithHeader(''clipboard'',''EM1e'',[-0.13,0.32,1.2,0.32])');
    uimenu(File(1),'Position',4,'Label','Print','Accelerator','P', ...
        'Callback','PrintWithHeader(''printer'',''EM1e'',[-0.13,0.32,1.2,0.32])');
    Help(1) = uimenu('Position',2,'Label','Help');
    uimenu(Help(1),'Position',1,'Label','About Error Plots', ...
        'Accelerator','H','Callback','AxesHelp(''about error'')');
    uimenu('Position',3,'Label','|');
    StdMenu(1) = uimenu('Position',4,'Label','MATLAB Menu');
    uimenu(StdMenu(1),'Position',1,'Label','Turn on', ...
        'Callback','set(gcf,''MenuBar'',''figure''); set(gcf,''Toolbar'',''figure'');');
    uimenu(StdMenu(1),'Position',2,'Label','Turn off', ...
        'Callback','set(gcf,''MenuBar'',''none''); set(gcf,''Toolbar'',''none'');');
    
    % title
    uicontrol(f_ErrorMon,'Style','text',...
        'String','Error Monitors',...
        'FontSize',20,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'Units','normalized',...
        'Position',[0.3 0.92 0.4 0.05]);
    % DOF 1 figures
    uicontrol(f_ErrorMon,'Style','text',...
        'Units','normalized',...
        'FontSize',15,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'String','DOF 1',...
        'Position',[0.227 0.85 0.1 0.05]);
    a_ErrorMonitors_eX = axes('Parent',f_ErrorMon,...
        'Tag','EM1e',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''e1'')',...
        'Position',[0.06 0.72 0.425 0.13],'Box','on',...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_eX,'Time [sec]');
    ylabel(a_ErrorMonitors_eX,'Disp Error [L]');
    a_ErrorMonitors_efX = axes('Parent',f_ErrorMon,...
        'Tag','EM1ffte',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''fft1'')',...
        'Position',[0.06 0.52 0.425 0.13],'Box','on',...
        'YScale','log');
    grid('on');
    xlabel(a_ErrorMonitors_efX,'Frequency [Hz]');
    ylabel(a_ErrorMonitors_efX,'Fourier Amp [L/sec]');
    a_ErrorMonitors_ddX = axes('Parent',f_ErrorMon,...
        'Tag','EM1MeasCmd',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''dd1'')',...
        'Position',[0.06 0.08 0.1875 0.38],'Box','on');
    %axis(a_ErrorMonitors_ddX,'equal');
    grid('on');
    xlabel(a_ErrorMonitors_ddX,'Command Disp [L]');
    ylabel(a_ErrorMonitors_ddX,'Measured Disp [L]');
    a_ErrorMonitors_etX = axes('Parent',f_ErrorMon,...
        'Tag','EM1track',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''TI1'')',...
        'Position',[0.2975 0.08 0.1875 0.38],'Box','on',...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_etX,'Time [sec]');
    ylabel(a_ErrorMonitors_etX,'Tracking Indicator [L^2]');
    
    % DOF 2 figures
    uicontrol(f_ErrorMon,'Style','text',...
        'Units','normalized',...
        'FontSize',15,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'String','DOF 2',...
        'Position',[0.712 0.85 0.1 0.05]);
    a_ErrorMonitors_eY = axes('Parent',f_ErrorMon,...
        'Tag','EM2e',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''e2'')',...
        'Position',[0.545 0.72 0.425 0.13],'Box','on',...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_eY,'Time [sec]');
    ylabel(a_ErrorMonitors_eY,'Disp Error [L]');
    a_ErrorMonitors_efY = axes('Parent',f_ErrorMon,...
        'Tag','EM2ffte',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''fft2'')',...
        'Position',[0.545 0.52 0.425 0.13],'Box','on',...
        'YScale','log');
    grid('on');
    xlabel(a_ErrorMonitors_efY,'Frequency [Hz]');
    ylabel(a_ErrorMonitors_efY,'Fourier Amp [L/sec]');
    a_ErrorMonitors_ddY = axes('Parent',f_ErrorMon,...
        'Tag','EM2MeasCmd',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''dd2'')',...
        'Position',[0.545 0.08 0.1875 0.38],'Box','on');
    %axis(a_ErrorMonitors_ddY,'equal');
    grid('on');
    xlabel(a_ErrorMonitors_ddY,'Command Disp [L]');
    ylabel(a_ErrorMonitors_ddY,'Measured Disp [L]');
    a_ErrorMonitors_etY = axes('Parent',f_ErrorMon,...
        'Tag','EM2track',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'ButtonDownFcn','AxesHelp(''TI2'')',...
        'Position',[0.7825 0.08 0.1875 0.38],'Box','on',...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_etY,'Time [sec]');
    ylabel(a_ErrorMonitors_etY,'Tracking Indicator [L^2]');
end
% =========================================================================
