function GUI_StructuralOutput(varargin)
% GUI_StructuralOutput provides layout of the GUI structural output page

% Check if window already exists
if ~isempty(findobj('Tag','StructOutDOF1'))
    figure(findobj('Tag','StructOutDOF1'));
    if ~isempty(findobj('Tag','StructOutDOF2'))
        figure(findobj('Tag','StructOutDOF2'));
        figure(findobj('Tag','StructOutDOF1'));
        return
    end
    return
end

%  Initialization tasks
handles = guidata(gcbf);

% find longest motion
tEnd = 0.0;
for mo=1:length(handles.GM.dt)
    tEndi = handles.GM.scalet{mo}(end);
    if tEndi > tEnd
        tEnd = tEndi;
    end
end

%%%%%%%%%%%%%%%%%
%Create figure 1%
%%%%%%%%%%%%%%%%%

%Main Figure
SS = get(0,'screensize');
f_StructOut1 = figure('Visible','on','Name','Structural Output',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Tag','StructOutDOF1',...
    'Color',[0.3 0.5 0.7],...
    'Position',[SS(3)*0.12,SS(4)*0.03,SS(3)*0.88,SS(4)*0.92]);

%Toolbar
% set(f_StructOut1,'Toolbar','figure');
% Toolbar_handles = findall(gcf);
% delete(Toolbar_handles([3:14 17:18]));
% set(Toolbar_handles(15), 'TooltipString', 'Print Window');
% set(Toolbar_handles(16), 'TooltipString', 'Save Window');
StdMenu(1) = uimenu('Position',1,'Label','MATLAB Menu');
StdMenu(2) = uimenu(StdMenu(1),'Position',1,'Label','Turn on', ...
   'Callback','set(gcf,''MenuBar'',''figure'');');
StdMenu(3) = uimenu(StdMenu(1),'Position',2,'Label','Turn off', ...
   'Callback','set(gcf,''MenuBar'',''none'');');
% =========================================================================

%Title
st_StructuralOut1_title = uicontrol(f_StructOut1,'Style','text',...
    'String','Structural Output',...
    'FontSize',20,...
    'ForegroundColor',[1 1 1],...
    'BackgroundColor',[0.3 0.5 0.7],...
    'Units','normalized',...
    'Position',[0.3 0.86 0.4 0.1],...
    'FontName',handles.Store.font);

%DOF 1 Output
a_StructuralOutput_dX = axes('Parent',f_StructOut1,...
    'Tag','SO1d',...
    'NextPlot','replacechildren',...
    'Position',[0.06 0.69 0.56 0.15],'Box','on','XTickLabel',[],...
    'XLimMode','manual','Xlim',[0.0 tEnd]);
grid('on');
ylabel(a_StructuralOutput_dX,'Disp [L]');
a_StructuralOutput_fX = axes('Parent',f_StructOut1,...
    'Tag','SO1f',...
    'NextPlot','replacechildren',...
    'Position',[0.06 0.49 0.56 0.15],'Box','on','XTickLabel',[],...
    'XLimMode','manual','Xlim',[0.0 tEnd]);
grid('on');
ylabel(a_StructuralOutput_fX,'Force [F]');
a_StructuralOutput_aX = axes('Parent',f_StructOut1,...
    'Tag','SO1a',...
    'NextPlot','replacechildren',...
    'Position',[0.06 0.29 0.56 0.15],'Box','on','XTickLabel',[],...
    'XLimMode','manual','Xlim',[0.0 tEnd]);
grid('on');
ylabel(a_StructuralOutput_aX,'Accel [L/sec^2]');
a_StructuralOutput_agX = axes('Parent',f_StructOut1,...
    'Tag','SO1ag',...
    'NextPlot','replacechildren',...
    'Position',[0.06 0.09 0.56 0.15],'Box','on');
line(handles.GM.scalet{1}, handles.GM.scaleag{1});
grid('on');
ylabel(a_StructuralOutput_agX,'Ground Accel [L/sec^2]');
xlabel(a_StructuralOutput_agX,'Time [sec]');
a_StructuralOutput_fdX = axes('Parent',f_StructOut1,...
    'Tag','SO1fd',...
    'NextPlot','replacechildren',...
    'Position',[0.68 0.09 0.3 0.75],'Box','on');
grid('on');
xlabel(a_StructuralOutput_fdX,'Disp [L]');
ylabel(a_StructuralOutput_fdX,'Force [F]');
if ~strcmp(handles.Model.Type, '1 DOF')
    set(a_StructuralOutput_fdX,'Position',[0.68 0.52 0.31 0.33]);
    a_StructuralOutput_dd = axes('Parent',f_StructOut1,...
        'Tag','SO1dd',...
        'NextPlot','replacechildren',...
        'Position',[0.68 0.08 0.31 0.33],'Box','on');
    axis(a_StructuralOutput_dd,'equal');
    grid('on');
    xlabel(a_StructuralOutput_dd,'Disp 1 [L]');
    ylabel(a_StructuralOutput_dd,'Disp 2 [L]');
end


%%%%%%%%%%%%%%%%%
%Create figure 2%
%%%%%%%%%%%%%%%%%

if ~strcmp(handles.Model.Type, '1 DOF')
    set(f_StructOut1,'Name','Structural Output DOF 1')
    set(st_StructuralOut1_title,'String','Structural Output: DOF 1');
    f_StructOut2 = figure('Visible','on','Name','Structural Output DOF 2',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'Tag','StructOutDOF2',...
        'Color',[0.3 0.5 0.7],...
        'Position',[SS(3)*0.12,SS(4)*0.03,SS(3)*0.88,SS(4)*0.92]);
    
    %Toolbar
%     set(f_StructOut2,'Toolbar','figure');
%     Toolbar_handles = findall(gcf);
%     delete(Toolbar_handles([3:14 17:18]));
%     set(Toolbar_handles(15), 'TooltipString', 'Print Report');
%     set(Toolbar_handles(16), 'TooltipString', 'Save Report');
    StdMenu(1) = uimenu('Position',1,'Label','MATLAB Menu');
    StdMenu(2) = uimenu(StdMenu(1),'Position',1,'Label','Turn on', ...
        'Callback','set(gcf,''MenuBar'',''figure'');');
    StdMenu(3) = uimenu(StdMenu(1),'Position',2,'Label','Turn off', ...
        'Callback','set(gcf,''MenuBar'',''none'');');
    
    %Title
    uicontrol(f_StructOut2,'Style','text',...
        'String','Structural Output: DOF 2',...
        'FontSize',20,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'Units','normalized',...
        'Position',[0.3 0.86 0.4 0.1],...
        'FontName',handles.Store.font);
    
    %DOF 2 Output
    a_StructuralOutput_dY = axes('Parent',f_StructOut2,...
        'Tag','SO2d',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.69 0.56 0.15],'Box','on','XTickLabel',[],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    ylabel(a_StructuralOutput_dY,'Disp [L]');
    a_StructuralOutput_fY = axes('Parent',f_StructOut2,...
        'Tag','SO2f',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.49 0.56 0.15],'Box','on','XTickLabel',[],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    ylabel(a_StructuralOutput_fY,'Force [F]');
    a_StructuralOutput_aY = axes('Parent',f_StructOut2,...
        'Tag','SO2a',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.29 0.56 0.15],'Box','on','XTickLabel',[],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    ylabel(a_StructuralOutput_aY,'Accel [L/sec^2]');
    a_StructuralOutput_agY = axes('Parent',f_StructOut2,...
        'Tag','SO2ag',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.09 0.56 0.15],'Box','on');
    if strcmp(handles.Model.Type, '2 DOF A')
        line(handles.GM.scalet{1}, handles.GM.scaleag{1});
    elseif strcmp(handles.Model.Type, '2 DOF B')
        line(handles.GM.scalet{2}, handles.GM.scaleag{2});
    end
    grid('on');
    ylabel(a_StructuralOutput_agY,'Ground Accel [L/sec^2]');
    xlabel(a_StructuralOutput_agY,'Time [sec]');
    a_StructuralOutput_fdY = axes('Parent',f_StructOut2,...
        'Tag','SO2fd',...
        'NextPlot','replacechildren',...
        'Position',[0.68 0.52 0.31 0.33],'Box','on');
    grid('on');
    xlabel(a_StructuralOutput_fdY,'Disp [L]');
    ylabel(a_StructuralOutput_fdY,'Force [F]');
    a_StructuralOutput_ff = axes('Parent',f_StructOut2,...
        'Tag','SO2ff',...
        'NextPlot','replacechildren',...
        'Position',[0.68 0.08 0.31 0.33],'Box','on');
    axis(a_StructuralOutput_ff,'equal');
    grid('on');
    xlabel(a_StructuralOutput_ff,'Force 1 [F]');
    ylabel(a_StructuralOutput_ff,'Force 2 [F]');
    
    %Bring DOF 1 image to the foreground
    figure(findobj('Tag','StructOutDOF1'));
end
