function GUI_AnalysisControls(varargin)
%GUI_ANALYSISCONTROLS to define the layout of of the analysis control tool
% GUI_AnalysisControls(varargin)
%
% varargin : variable length input argument list
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                          OpenFresco Express                          %%
%%    GUI for the Open Framework for Experimental Setup and Control     %%
%%                                                                      %%
%%   (C) Copyright 2011, The Pacific Earthquake Engineering Research    %%
%%            Center (PEER) & MTS Systems Corporation (MTS)             %%
%%                         All Rights Reserved.                         %%
%%                                                                      %%
%%     Commercial use of this program without express permission of     %%
%%                 PEER and MTS is strictly prohibited.                 %%
%%     See Help -> OpenFresco Express Disclaimer for information on     %%
%%   usage and redistribution, and for a DISCLAIMER OF ALL WARRANTIES.  %%
%%                                                                      %%
%%   Developed by:                                                      %%
%%     Andreas Schellenberg (andreas.schellenberg@gmail.com)            %%
%%     Carl Misra (carl.misra@gmail.com)                                %%
%%     Stephen A. Mahin (mahin@berkeley.edu)                            %%
%%                                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% $Revision$
% $Date$
% $URL$

% Check if window already exists
if ~isempty(findobj('Tag','AnalysisControls'))
    figure(findobj('Tag','AnalysisControls'));
    return
end

%  Initialization tasks
handles = guidata(gcbf);
panel_color = [0.3 0.5 0.7];%Replace with handles.panelColor

%Main Figure
f_AnalysisControls = figure('Visible','on','Name','Analysis Controls',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Tag','AnalysisControls',...
    'Color',[0.3 0.5 0.7],...
    'Resize','off',...
    'Position',[handles.Store.SS(3)*0.01,handles.Store.SS(4)*0.71,handles.Store.SS(3)*0.10,handles.Store.SS(4)*0.265]);

handles.Sidebar(3) = uibuttongroup('Parent',f_AnalysisControls,...
    'BackgroundColor',panel_color,...
    'Visible','on',...
    'Tag','ControlPanel',...
    'Position',[0.03 .03 .94 .94]);
         handles.Sidebar(4) = uicontrol(handles.Sidebar(3),'Style','togglebutton',...
             'Units','normalized',...
             'Tag','Start',...
             'Position',[0.08 0.66 0.84 0.3],...
             'ToolTipString','Start Analysis',...
             'CData',handles.Store.Start0b);
         handles.Sidebar(5) = uicontrol(handles.Sidebar(3),'Style','togglebutton',...
             'Units','normalized',...
             'Tag','Pause',...
             'Position',[0.08 0.34 0.84 0.3],...
             'ToolTipString','Pause Analysis',...
             'CData',handles.Store.Pause0b);
         handles.Sidebar(6) = uicontrol(handles.Sidebar(3),'Style','togglebutton',...
             'Units','normalized',...
             'Tag','Stop',...
             'ToolTipString','Stop Analysis',...
             'Position',[0.08 0.03 0.84 0.3],...
             'CData',handles.Store.Stop0b);
         align(handles.Sidebar(4:6),'None','Fixed',3);
         set(handles.Sidebar(3),'SelectionChangeFcn','Analysis(''choose option'')');
         set(handles.Sidebar(3),'SelectedObject',[]);
         
%Update handles structure
guidata(gcbf, handles);

end
