function GUI_StructuralOutput(varargin)
%GUI_STRUCTURALOUTPUT to define the layout of the structural output page
% GUI_StructuralOutput(varargin)
%
% varargin : variable length input argument list
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                          OpenFresco Express                          %%
%%    GUI for the Open Framework for Experimental Setup and Control     %%
%%                                                                      %%
%%   (C) Copyright 2011, The Pacific Earthquake Engineering Research    %%
%%            Center (PEER) & MTS Systems Corporation (MTS)             %%
%%                         All Rights Reserved.                         %%
%%                                                                      %%
%%     Commercial use of this program without express permission of     %%
%%                 PEER and MTS is strictly prohibited.                 %%
%%     See Help -> OpenFresco Express Disclaimer for information on     %%
%%   usage and redistribution, and for a DISCLAIMER OF ALL WARRANTIES.  %%
%%                                                                      %%
%%   Developed by:                                                      %%
%%     Andreas Schellenberg (andreas.schellenberg@gmail.com)            %%
%%     Carl Misra (carl.misra@gmail.com)                                %%
%%     Stephen A. Mahin (mahin@berkeley.edu)                            %%
%%                                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% $Revision$
% $Date$
% $URL$

% check if window already exists
if ~isempty(findobj('Tag','StructOutDOF1'))
    if ~isempty(findobj('Tag','StructOutDOF2'))
        figure(findobj('Tag','StructOutDOF2'));
    end
    figure(findobj('Tag','StructOutDOF1'));
    return
end

% initialization tasks
handles = guidata(findobj('Tag','OpenFrescoExpress'));
SS = handles.Store.SS;

% find longest motion
tEnd = 0.0;
switch handles.GM.loadType
    case 'Ground Motions'
        numMotions = size(handles.Model.b,2);
        for mo=1:numMotions
            tEndi = handles.GM.scalet{mo}(end);
            if tEndi > tEnd
                tEnd = tEndi;
            end
        end
    case 'Initial Conditions'
        tEnd = handles.GM.rampTime + handles.GM.vibTime;
end

% =====================================================================
% create figure 1
f_StructOut1 = figure('Name','Structural Output',...
    'Visible','on',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Tag','StructOutDOF1',...
    'Color',[0.3 0.5 0.7],...
    'Position',[SS(3)*0.12,SS(4)*0.05,SS(3)*0.87,SS(4)*0.87]);
orient(f_StructOut1,'landscape');
ModifyPrintSetup(f_StructOut1,'PrintUI',0);

% toolbar
File(1) = uimenu('Position',1,'Label','File');
uimenu(File(1),'Position',1,'Label','Save As FIG','Accelerator','M', ...
    'Callback','PrintWithHeader(''fig'',''SO1d'',[-0.1,0.25,0.67,0.25])');
uimenu(File(1),'Position',2,'Label','Save As PDF','Accelerator','S', ...
    'Callback','PrintWithHeader(''pdf'',''SO1d'',[-0.1,0.25,0.67,0.25])');
uimenu(File(1),'Position',3,'Label','Copy','Accelerator','C', ...
    'Callback','PrintWithHeader(''clipboard'',''SO1d'',[-0.1,0.25,0.67,0.25])');
uimenu(File(1),'Position',4,'Label','Print','Accelerator','P', ...
    'Callback','PrintWithHeader(''printer'',''SO1d'',[-0.1,0.25,0.67,0.25])');
uimenu('Position',2,'Label','|');
StdMenu(1) = uimenu('Position',3,'Label','MATLAB Menu');
uimenu(StdMenu(1),'Position',1,'Label','Turn on',...
    'Callback','set(gcf,''MenuBar'',''figure''); set(gcf,''Toolbar'',''figure'');');
uimenu(StdMenu(1),'Position',2,'Label','Turn off',...
    'Callback','set(gcf,''MenuBar'',''none''); set(gcf,''Toolbar'',''none'');');

% title
st_StructuralOut1_title = uicontrol(f_StructOut1,'Style','text',...
    'String','Structural Output',...
    'FontSize',20,...
    'ForegroundColor',[1 1 1],...
    'BackgroundColor',[0.3 0.5 0.7],...
    'Units','normalized',...
    'Position',[0.3 0.86 0.4 0.1],...
    'FontName',handles.Store.font);

% DOF 1 output
a_StructuralOutput_dX = axes('Parent',f_StructOut1,...
    'Tag','SO1d',...
    'NextPlot','replacechildren',...
    'FontWeight','bold',...
    'Position',[0.06 0.69 0.56 0.15],'Box','on','XTickLabel',[],...
    'XLimMode','manual','Xlim',[0.0 tEnd]);
grid('on');
ylabel(a_StructuralOutput_dX,'Disp [L]');
a_StructuralOutput_fX = axes('Parent',f_StructOut1,...
    'Tag','SO1f',...
    'NextPlot','replacechildren',...
    'FontWeight','bold',...
    'Position',[0.06 0.49 0.56 0.15],'Box','on','XTickLabel',[],...
    'XLimMode','manual','Xlim',[0.0 tEnd]);
grid('on');
ylabel(a_StructuralOutput_fX,'Force [F]');
a_StructuralOutput_aX = axes('Parent',f_StructOut1,...
    'Tag','SO1a',...
    'NextPlot','replacechildren',...
    'FontWeight','bold',...
    'Position',[0.06 0.29 0.56 0.15],'Box','on','XTickLabel',[],...
    'XLimMode','manual','Xlim',[0.0 tEnd]);
grid('on');
ylabel(a_StructuralOutput_aX,'Accel [L/sec^2]');
a_StructuralOutput_agX = axes('Parent',f_StructOut1,...
    'Tag','SO1ag',...
    'NextPlot','replacechildren',...
    'FontWeight','bold',...
    'Position',[0.06 0.09 0.56 0.15],'Box','on');
switch handles.GM.loadType
    case 'Ground Motions'
        line(handles.GM.scalet{1}, handles.GM.scaleag{1});
        grid('on');
        ylabel(a_StructuralOutput_agX,'Ground Accel [L/sec^2]');
        xlabel(a_StructuralOutput_agX,'Time [sec]');
        set(findobj('Tag','SO1ag'),'XLimMode','manual','Xlim',[0.0 tEnd]);
    case 'Initial Conditions'
        set(findobj('Tag','SO1ag'),'YLimMode','manual','Ylim',[-100 100],'YTick', [-100 0 100])
        xValues = [0 handles.GM.rampTime handles.GM.rampTime (handles.GM.rampTime+handles.GM.vibTime)];
        yValues = [0 100 0 0];
        line(xValues, yValues);
        grid('on');
        ylabel(a_StructuralOutput_agX,'% Total Displacement');
        xlabel(a_StructuralOutput_agX,'Time [sec]');
end

linkaxes([a_StructuralOutput_dX, a_StructuralOutput_fX, a_StructuralOutput_aX, a_StructuralOutput_agX],'x');

a_StructuralOutput_fdX = axes('Parent',f_StructOut1,...
    'Tag','SO1fd',...
    'NextPlot','replacechildren',...
    'FontWeight','bold',...
    'Position',[0.68 0.09 0.29 0.75],'Box','on');
grid('on');
xlabel(a_StructuralOutput_fdX,'Disp [L]');
ylabel(a_StructuralOutput_fdX,'Force [F]');
if ~strcmp(handles.Model.Type, '1 DOF')
    set(a_StructuralOutput_fdX,'Position',[0.68 0.52 0.29 0.33]);
    a_StructuralOutput_dd = axes('Parent',f_StructOut1,...
        'Tag','SO1dd',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'Position',[0.68 0.08 0.29 0.33],'Box','on');
    axis(a_StructuralOutput_dd,'equal');
    grid('on');
    xlabel(a_StructuralOutput_dd,'Disp 1 [L]');
    ylabel(a_StructuralOutput_dd,'Disp 2 [L]');
end

% =====================================================================
% create figure 2
if ~strcmp(handles.Model.Type, '1 DOF')
    % main figure
    set(f_StructOut1,'Name','Structural Output DOF 1')
    set(st_StructuralOut1_title,'String','Structural Output: DOF 1');
    f_StructOut2 = figure('Name','Structural Output DOF 2',...
        'Visible','on',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'Tag','StructOutDOF2',...
        'Color',[0.3 0.5 0.7],...
        'Position',[SS(3)*0.12,SS(4)*0.05,SS(3)*0.87,SS(4)*0.87]);
    orient(f_StructOut2,'landscape');
    ModifyPrintSetup(f_StructOut2,'PrintUI',0);
    
    % toolbar
    File(1) = uimenu('Position',1,'Label','File');
    uimenu(File(1),'Position',1,'Label','Save As FIG','Accelerator','M', ...
        'Callback','PrintWithHeader(''fig'',''SO2d'',[-0.1,0.25,0.67,0.25])');
    uimenu(File(1),'Position',2,'Label','Save As PDF','Accelerator','S', ...
        'Callback','PrintWithHeader(''pdf'',''SO2d'',[-0.1,0.25,0.67,0.25])');
    uimenu(File(1),'Position',3,'Label','Copy','Accelerator','C', ...
        'Callback','PrintWithHeader(''clipboard'',''SO2d'',[-0.1,0.25,0.67,0.25])');
    uimenu(File(1),'Position',4,'Label','Print','Accelerator','P', ...
        'Callback','PrintWithHeader(''printer'',''SO2d'',[-0.1,0.25,0.67,0.25])');
    uimenu('Position',2,'Label','|');
    StdMenu(1) = uimenu('Position',3,'Label','MATLAB Menu');
    uimenu(StdMenu(1),'Position',1,'Label','Turn on', ...
        'Callback','set(gcf,''MenuBar'',''figure''); set(gcf,''Toolbar'',''figure'');');
    uimenu(StdMenu(1),'Position',2,'Label','Turn off', ...
        'Callback','set(gcf,''MenuBar'',''none''); set(gcf,''Toolbar'',''none'');');
    
    % title
    uicontrol(f_StructOut2,'Style','text',...
        'String','Structural Output: DOF 2',...
        'FontSize',20,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'Units','normalized',...
        'Position',[0.3 0.86 0.4 0.1],...
        'FontName',handles.Store.font);
    
    % DOF 2 output
    a_StructuralOutput_dY = axes('Parent',f_StructOut2,...
        'Tag','SO2d',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'Position',[0.06 0.69 0.56 0.15],'Box','on','XTickLabel',[],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    ylabel(a_StructuralOutput_dY,'Disp [L]');
    a_StructuralOutput_fY = axes('Parent',f_StructOut2,...
        'Tag','SO2f',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'Position',[0.06 0.49 0.56 0.15],'Box','on','XTickLabel',[],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    ylabel(a_StructuralOutput_fY,'Force [F]');
    a_StructuralOutput_aY = axes('Parent',f_StructOut2,...
        'Tag','SO2a',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'Position',[0.06 0.29 0.56 0.15],'Box','on','XTickLabel',[],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    ylabel(a_StructuralOutput_aY,'Accel [L/sec^2]');
    a_StructuralOutput_agY = axes('Parent',f_StructOut2,...
        'Tag','SO2ag',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'Position',[0.06 0.09 0.56 0.15],'Box','on');
    switch handles.GM.loadType
        case 'Ground Motions'
            if strcmp(handles.Model.Type, '2 DOF A')
                line(handles.GM.scalet{1}, handles.GM.scaleag{1});
            elseif strcmp(handles.Model.Type, '2 DOF B')
                line(handles.GM.scalet{2}, handles.GM.scaleag{2});
            end
            grid('on');
            ylabel(a_StructuralOutput_agY,'Ground Accel [L/sec^2]');
            xlabel(a_StructuralOutput_agY,'Time [sec]');
            set(findobj('Tag','SO1ag'),'XLimMode','manual','Xlim',[0.0 tEnd]);
        case 'Initial Conditions'
            set(findobj('Tag','SO2ag'),'YLimMode','manual','Ylim',[-100 100],'YTick', [-100 0 100])
            xValues = [0 handles.GM.rampTime handles.GM.rampTime (handles.GM.rampTime+handles.GM.vibTime)];
            yValues = [0 100 0 0];
            line(xValues, yValues);
            grid('on');
            ylabel(a_StructuralOutput_agY,'% Total Displacement');
            xlabel(a_StructuralOutput_agY,'Time [sec]');
    end
    
    linkaxes([a_StructuralOutput_dY, a_StructuralOutput_fY, a_StructuralOutput_aY, a_StructuralOutput_agY],'x');
    
    a_StructuralOutput_fdY = axes('Parent',f_StructOut2,...
        'Tag','SO2fd',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'Position',[0.68 0.52 0.29 0.33],'Box','on');
    grid('on');
    xlabel(a_StructuralOutput_fdY,'Disp [L]');
    ylabel(a_StructuralOutput_fdY,'Force [F]');
    a_StructuralOutput_ff = axes('Parent',f_StructOut2,...
        'Tag','SO2ff',...
        'NextPlot','replacechildren',...
        'FontWeight','bold',...
        'Position',[0.68 0.08 0.29 0.33],'Box','on');
    axis(a_StructuralOutput_ff,'equal');
    grid('on');
    xlabel(a_StructuralOutput_ff,'Force 1 [F]');
    ylabel(a_StructuralOutput_ff,'Force 2 [F]');
    
    % bring DOF 1 output to the foreground
    figure(findobj('Tag','StructOutDOF1'));
end
% =====================================================================
