function OpenFrescoExpress(action)
%OPENFRESCOEXPRESS to launch OpenFrescoExpress and display the disclaimer
% OpenFrescoExpress(action)
%
% action : switch with following possible values
%             'startup'  to show disclaimer during startup
%             'about'    to show disclaimer from the help menu
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                          OpenFresco Express                          %%
%%    GUI for the Open Framework for Experimental Setup and Control     %%
%%                                                                      %%
%%   (C) Copyright 2011, The Pacific Earthquake Engineering Research    %%
%%            Center (PEER) & MTS Systems Corporation (MTS)             %%
%%                         All Rights Reserved.                         %%
%%                                                                      %%
%%     Commercial use of this program without express permission of     %%
%%                 PEER and MTS is strictly prohibited.                 %%
%%     See Help -> OpenFresco Express Disclaimer for information on     %%
%%   usage and redistribution, and for a DISCLAIMER OF ALL WARRANTIES.  %%
%%                                                                      %%
%%   Developed by:                                                      %%
%%     Andreas Schellenberg (andreas.schellenberg@gmail.com)            %%
%%     Carl Misra (carl.misra@gmail.com)                                %%
%%     Stephen A. Mahin (mahin@berkeley.edu)                            %%
%%                                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% $Revision$
% $Date$
% $URL$

if (nargin==0)
    action = 'startup';
end

if ~isempty(findobj('Tag','Copyright'))
    figure(findobj('Tag','Copyright'));
    return
end

% copyright screen size
SS = get(0,'screensize');
Width = 0.5*SS(3);
Height = 0.5*SS(4);

switch action
    %=========================================================================
    case 'startup'
        % display message at cmd prompt
        clc;
        fprintf(1,['Starting OpenFresco Express ......\n'...
            'Please be patient, this may take a while.\n']);
        % create window
        figure('Name','Copyright & Disclaimer', ...
            'NumberTitle','off', ...
            'Color',[0.3 0.5 0.7], ...
            'MenuBar','none', ...
            'Tag','Copyright', ...
            'Position',[(SS(3)-Width)/2 0.258*SS(4) Width Height]);
        uicontrol('Style','text', ...
            'Units','pixels', ...
            'Position',[0 0.89*Height Width 0.06*Height], ...
            'String','Copyright & Disclaimer', ...
            'FontUnits','pixels','FontWeight','normal','FontSize',25,'FontName','Arial', ...
            'BackgroundColor',[0.3 0.5 0.7],'ForegroundColor','w','Horizontal','center');
        uicontrol('Style','edit', ...
            'Max',10,'Min',1, ...
            'Units','pixels', ...
            'Position',[0.075*Width 0.2*Height 0.85*Width 0.65*Height], ...
            'String',fileread('OPFE_Copyright.txt'), ...
            'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height, ...
            'FontName','Arial','BackgroundColor','w','ForegroundColor','k', ...
            'Horizontal','left');
        
        % accept button
        callbackStr = 'close(findobj(''Tag'',''Copyright'')); drawnow; GUI_Template; clc;';
        uicontrol('Style','pushbutton', ...
            'Units','pixels', ...
            'Position',[0.3*Width-0.2*Width/2 0.05*Height 0.2*Width 0.075*Height], ...
            'String','I accept', ...
            'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height,...
            'Horizontal','center','Callback',callbackStr);
        
        % decline button
        callbackStr = 'close(findobj(''Tag'',''Copyright''));';
        uicontrol('Style','pushbutton', ...
            'Units','pixels', ...
            'Position',[0.7*Width-0.2*Width/2 0.05*Height 0.2*Width 0.075*Height], ...
            'String','I decline', ...
            'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height,...
            'Horizontal','center','Callback',callbackStr);
    %=========================================================================
    case 'about'
        % create window
        figure('Name','Copyright & Disclaimer', ...
            'NumberTitle','off', ...
            'Color',[0.3 0.5 0.7], ...
            'MenuBar','none', ...
            'Tag','Copyright', ...
            'Position',[0.303*SS(3) 0.258*SS(4) Width Height]);
        uicontrol('Style','text', ...
            'Units','pixels', ...
            'Position',[0 0.89*Height Width 0.06*Height], ...
            'String','Copyright & Disclaimer', ...
            'FontUnits','pixels','FontWeight','normal','FontSize',25,'FontName','Arial', ...
            'BackgroundColor',[0.3 0.5 0.7],'ForegroundColor','w','Horizontal','center');
        uicontrol('Style','edit', ...
            'Max',10,'Min',1, ...
            'Units','pixels', ...
            'Position',[0.075*Width 0.2*Height 0.85*Width 0.65*Height], ...
            'String',fileread('OPFE_Copyright.txt'), ...
            'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height, ...
            'FontName','Arial','BackgroundColor','w','ForegroundColor','k', ...
            'Horizontal','left');
        
        % close button
        callbackStr = 'close(findobj(''Tag'',''Copyright''));';
        uicontrol('Style','pushbutton', ...
            'Units','pixels', ...
            'Position',[0.5*Width-0.2*Width/2 0.05*Height 0.2*Width 0.075*Height], ...
            'String','close', ...
            'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height,...
            'Horizontal','center','Callback',callbackStr);
    %=========================================================================
end

%#function Analysis AnimateResponse AxesHelp DisplayAxes 
%#function Element_ExpGeneric ExpControl ExpSetup ExpSite 
%#function GUI_AnalysisControls GUI_AnimateStructure GUI_ErrorMonitors GUI_Output 
%#function GUI_StructuralOutput GUI_Template GetFFT GroundMotions 
%#function InputCheck Integrator_AlphaOS Integrator_NewmarkExplicit Links 
%#function MenuBar ModifyPrintSetup OpenFrescoExpress PrintWithHeader 
%#function ReadWriteTHFile ReplayResults Report ResizeImage 
%#function RunOpenFresco SetOPFPath SplashScreen Structure 
%#function TCPSocket TerminateAnalysis UDPSocket WriteTCL 