function OPFQuickStart(action)

if (nargin==0)
    action = 'startup';
end

% text for disclaimer
TEXT = ['\nThe University of California, the Pacific Earthquake Engineering Research Center (PEER) and the authors ' ...
        'provide this software without a signed license. It is distributed by The Regents of the ' ...
        'University of California (UC Regents) "as is," as a public service, without any additional ' ...
        'services from, or licensing by, the UC Regents. The program has been developed by researchers ' ...
        'at PEER. UC Regents, PEER and the authors do not warrant ' ...
        'that the operation of the program will be uninterrupted or error-free. \n\n' ...
        'IN NO EVENT SHALL THE UC REGENTS OR PEER OR THE AUTHORS BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, '...
        'INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS ' ...
        'SOFTWARE, EVEN IF THE UNIVERSITY OF CALIFORNIA OR PEER OR THE AUTHORS HAVE BEEN ADVISED OF THE POSSIBILITY OF ' ...
        'SUCH DAMAGE. \n\n' ...
        'THE UC REGENTS, PEER AND THE AUTHORS SPECIFICALLY DISCLAIM ANY WARRANTIES, INCLUDING BUT NOT LIMITED TO,' ...
        'THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. NEITHER THE '...
        'UC REGENTS NOR PEER NOR THE AUTHORS REPRESENT OR WARRANT THAT THE PROGRAM DOES NOT INFRINGE THE INTELLECTUAL '...
        'PROPERTY, PROPRIETARY OR CONTRACTUAL RIGHTS OF THIRD PARTIES. THE SOFTWARE PROVIDED HEREUNDER '...
        'IS ON AN "AS IS" BASIS, AND THE UC REGENTS AND PEER AND THE AUTHORS HAVE NO OBLIGATIONS TO PROVIDE MAINTENANCE, '...
        'SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.'];

% disclaimer screen size
SS = get(0,'screensize');
Width = 0.5*SS(3);
Height = 0.5*SS(4);

% create window
fDisclaimer = figure('Name','Disclaimer',...
           'NumberTitle','off',...
           'Color',[0.3 0.5 0.7],...
           'MenuBar','none',...
           'Tag','Disclaimer',...
           'Position',[0.3*SS(3) 0.25*SS(4) Width Height]);
uicontrol('Style','text', ...
    'Units','pixels', ...
    'Position',[0 0.89*Height Width 0.05*Height], ...
    'String','Disclaimer', ...
    'FontUnits','pixels','FontWeight','normal','FontSize',25,'FontName','Arial',...
    'BackgroundColor',[0.3 0.5 0.7],'ForegroundColor','w','Horizontal','center');
uicontrol('Style','text', ...
    'Units','pixels', ...
    'Position',[0.075*Width 0.2*Height 0.85*Width 0.65*Height], ...
    'String',sprintf(TEXT), ...
    'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor','k','Horizontal','left');

% uicontrol('Style','pushbutton', ...
%     'Units','normalized', ...
%     'Position',[0.075*Width 0.2*Height 0.85*Width 0.65*Height], ...
%     'String',', ...
%     'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height,'FontName','Arial', ...
%     'BackgroundColor','w','ForegroundColor','k','Horizontal','left');
% 'Style','pushbutton',...
%     'String','User Tips',...
%     'Units','normalized',...
%     'BackgroundColor',panel_color,...
%     'Callback','Links(''User Tips'')',...
%     'Position',[0.03 0.36 0.1 0.04]);

switch action
    %=========================================================================
    case 'startup'
        % Accept button
        callbackStr = 'close(findobj(''Tag'',''Disclaimer'')); GUI_Template;';
        uicontrol('Style','pushbutton', ...
            'Units','pixels', ...
            'Position',[0.3*Width-0.2*Width/2 0.05*Height 0.2*Width 0.075*Height], ...
            'String','I accept', ...
            'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height,'Horizontal','center',...
            'Callback',callbackStr);
        
        % Decline button
        callbackStr = 'close(findobj(''Tag'',''Disclaimer''));';
        uicontrol('Style','pushbutton', ...
            'Units','pixels', ...
            'Position',[0.7*Width-0.2*Width/2 0.05*Height 0.2*Width 0.075*Height], ...
            'String','I decline', ...
            'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height,'Horizontal','center',...
            'Callback',callbackStr);
    %=========================================================================
    case 'about'
        % Close button
        callbackStr = 'close(findobj(''Tag'',''Disclaimer''));';
        uicontrol('Style','pushbutton', ...
            'Units','pixels', ...
            'Position',[0.5*Width-0.2*Width/2 0.05*Height 0.2*Width 0.075*Height], ...
            'String','close', ...
            'FontUnits','pixels','FontWeight','bold','FontSize',0.025*Height,'Horizontal','center',...
            'Callback',callbackStr);
   %=========================================================================
end