function SplashScreen(action)

% show splash screen
SS = get(0,'screensize');
Width = 0.8*0.81*0.92*SS(3);
Height = 0.8*0.9*0.88*SS(4);

% create window
fSplash = figure('NumberTitle','off',...
           'Color','w',...
           'MenuBar','none',...
           'Tag','SplashScreen',...
           'Position',[0.25*SS(3) 0.18*SS(4) Width Height]);

uicontrol('Style','text', ...
   'Units','normalized', ...
   'Position',[0.0 0.75 1.0 0.2], ...
   'String','OpenFresco Quick Start', ...
   'FontUnits','normalized','FontWeight','bold','FontSize',0.50,'FontName','Arial',...
   'BackgroundColor','w','ForegroundColor',rand(3,1),'Horizontal','center');
uicontrol('Style','text', ...
   'Units','normalized', ...
   'Position',[0.0 0.773 1.0 0.05], ...
   'String',['Release: December 2010'], ...
   'FontUnits','normalized','FontWeight','bold','FontSize',0.65,'FontName','Arial', ...
   'BackgroundColor','w','ForegroundColor','r','Horizontal','center');
uicontrol('Style','text', ...
   'Units','normalized', ...
   'Position',[0.0 0.51 1.0 0.2], ...
   'String',sprintf('Developed by'),...
   'FontUnits','normalized','FontWeight','bold','FontSize',0.15,'FontName','Arial', ...
   'BackgroundColor','w','ForegroundColor','k','Horizontal','center');
uicontrol('Style','text', ...
   'Units','normalized', ...
   'Position',[0.147 0.495 0.28 0.15], ...
   'String',sprintf('Andreas Schellenberg, Ph.D. \n Dep. of Civil and Env. Eng. \n University of California, Berkeley'),...
   'FontUnits','normalized','FontWeight','bold','FontSize',0.175,'FontName','Arial', ...
   'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
uicontrol('Style','text', ...
   'Units','normalized', ...
   'Position',[0.574 0.495 0.28 0.15], ...
   'String',sprintf('Carl Misra, M.S. \n Dep. of Civil and Env. Eng. \n University of California, Berkeley'),...
   'FontUnits','normalized','FontWeight','bold','FontSize',0.175,'FontName','Arial', ...
   'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
% uicontrol('Style','text', ...
%    'Units','normalized', ...
%    'Position',[0.665 0.495 0.28 0.15], ...
%    'String',sprintf('Professor St \n Geo. and Structural Eng. Dep. \n Port and Airport Research Institute'),...
%    'FontUnits','normalized','FontWeight','bold','FontSize',0.175,'FontName','Arial', ...
%    'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
uicontrol('Style','text', ...
   'Units','normalized', ...
   'Position',[0.25 0.39 0.5 0.1], ...
   'String',sprintf('OpenFresco Quick Start is supported by funds from'), ...
   'FontUnits','normalized','FontWeight','bold','FontSize',0.3,'FontName','Arial', ...
   'BackgroundColor','w','ForegroundColor','k','Horizontal','center');
uicontrol('Style','text', ...
   'Units','normalized', ...
   'Position',[0.1 0.28 0.80 0.15], ...
   'String',sprintf('MTS Systems Corporation\n The Pacific Earthquake Engineering Research (PEER) Center'), ...
   'FontUnits','normalized','FontWeight','bold','FontSize',0.18,'FontName','Arial', ...
   'BackgroundColor','w','ForegroundColor','k','Horizontal','center');
uicontrol('Style','text', ...
   'Units','normalized', ...
   'Position',[0.0 0.0 1.0 0.05], ...
   'String',sprintf('(C) Copyright 2010, The Regents of the University of California. All Rights Reserved.'),...
   'FontUnits','normalized','FontWeight','bold','FontSize',0.5,'FontName','Arial', ...
   'BackgroundColor','w','ForegroundColor','k','Horizontal','center');

% load MTS logo
axes('Position',[0.31 0.14 0.11 0.11],...
   'Color','white','XTick',[],'YTick',[]);
banner = imread(which('MTSWhite.png'));
image(banner);
axis equal; axis off;

% load PEER logo
axes('Position',[0.56 0.12 0.14 0.14],...
   'Color','white','XTick',[],'YTick',[]);
banner = imread(which('PEERWhite.png'));
image(banner);
axis equal; axis off;


switch action
   case 'startup'
      set(findobj('Tag','SplashScreen'),'CloseRequestFcn','');
      pause(0.25);
      figure(findobj('Tag','SplashScreen'));
      pause(2.5);
      delete(findobj('Tag','SplashScreen'));
   case 'about'
      % do nothing
end
