%CREATEEXECUTABLE to create a standalone executable of the OpenFresco GUI
% CreateExecutable
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                          OpenFresco Express                          %%
%%    GUI for the Open Framework for Experimental Setup and Control     %%
%%                                                                      %%
%%   (C) Copyright 2011, The Pacific Earthquake Engineering Research    %%
%%            Center (PEER) & MTS Systems Corporation (MTS)             %%
%%                         All Rights Reserved.                         %%
%%                                                                      %%
%%     Commercial use of this program without express permission of     %%
%%                 PEER and MTS is strictly prohibited.                 %%
%%     See Help -> OpenFresco Express Disclaimer for information on     %%
%%   usage and redistribution, and for a DISCLAIMER OF ALL WARRANTIES.  %%
%%                                                                      %%
%%   Developed by:                                                      %%
%%     Andreas Schellenberg (andreas.schellenberg@gmail.com)            %%
%%     Carl Misra (carl.misra@gmail.com)                                %%
%%     Stephen A. Mahin (mahin@berkeley.edu)                            %%
%%                                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% $Revision$
% $Date$
% $URL$

% clean start
clear all; close all; clc;

% get path to OPF directory
pathOPF = which('OPFE_Version.txt');
pathOPF = fileparts(pathOPF);

% update PragmaList
UpdatePragmaList(pathOPF);

% set directory for src
pathSRC = fullfile(pathOPF,'Deployment','src');

% change the current directory
cd(pathSRC);

% invoke MATLAB to C/C++ compiler
if ispc
    mcc -mv OpenFrescoExpress.m ...
        -a AboutErrorMonitors.txt ...
        -a OPFE_Copyright.txt ...
        -a OPFE_Version.txt ...
        -a ResponseSpectraElastic.mexw32 ...
        -a ResponseSpectraElastic.mexw64 ...
        -a TCPSocket.mexw32 ...
        -a TCPSocket.mexw64 ...
        -a UDPSocket.mexw32 ...
        -a UDPSocket.mexw64 ...
        -a Metal.jpg ...        % ..\Buttons\
        -a Analysis0.png ...
        -a Analysis1.png ...
        -a BlueGradient.png ...
        -a ControlPoint0.png ...
        -a ControlPoint1.png ...
        -a Distributed0.png ...
        -a Distributed1.png ...
        -a ESModel1A0.png ...
        -a ESModel1A1.png ...
        -a ESModel2A0.png ...
        -a ESModel2A1.png ...
        -a ESModel2B0.png ...
        -a ESModel2B1.png ...
        -a ExpControl0.png ...
        -a ExpControl1.png ...
        -a ExpSetup0.png ...
        -a ExpSetup1.png ...
        -a ExpSite0.png ...
        -a ExpSite1.png ...
        -a FreeVibration.png ...
        -a GreyGradient.png ...
        -a GroundMotions0.png ...
        -a GroundMotions1.png ...
        -a InitialConditions0.png ...
        -a InitialConditions1.png ...
        -a Loading0.png ...
        -a Loading1.png ...
        -a Local0.png ...
        -a Local1.png ...
        -a Model1A0.png ...
        -a Model1A1.png ...
        -a Model2A0.png ...
        -a Model2A1.png ...
        -a Model2B0.png ...
        -a Model2B1.png ...
        -a MTSMetal.png ...
        -a MTSWhite.png ...
        -a Pause0.png ...
        -a Pause1.png ...
        -a PEERBoldMetal.png ...
        -a PEERBoldWhite.png ...
        -a Question0.png ...
        -a Question1.png ...
        -a RealController0.png ...
        -a RealController1.png ...
        -a Simulation0.png ...
        -a Simulation1.png ...
        -a Start0.png ...
        -a Start1.png ...
        -a Stop0.png ...
        -a Stop1.png ...
        -a Structure0.png ...
        -a Structure1.png ...
        -a Dscoml32.dll ...     % ..\WIN32\bin
        -a genutil.dll ...
        -a libeay32.dll ...
        -a Link.dll ...
        -a mts32olv.dll ...
        -a MtsCsiCom.dll ...
        -a mtslibXml2.dll ...
        -a mtsvw001.dll ...
        -a OpenFresco.dll ...
        -a openSees.exe ...
        -a Pnpscr.dll ...
        -a PNPSCRD.dll ...
        -a Rt.dll ...
        -a rtnote.dll ...
        -a ssleay32.dll ...
        -a taskfinder.dll ...
        -a xpcapi.dll;
elseif ismac || isunix
    mcc -mv OpenFrescoExpress.m ...
        -a AboutErrorMonitors.txt ...
        -a OPFE_Copyright.txt ...
        -a OPFE_Version.txt ...
        -a ResponseSpectraElastic.mexmaci ...
        -a TCPSocket.mexmaci ...
        -a UDPSocket.mexmaci ...
        -a Metal.jpg ...        % ..\Buttons\
        -a Analysis0.png ...
        -a Analysis1.png ...
        -a BlueGradient.png ...
        -a ControlPoint0.png ...
        -a ControlPoint1.png ...
        -a Distributed0.png ...
        -a Distributed1.png ...
        -a ESModel1A0.png ...
        -a ESModel1A1.png ...
        -a ESModel2A0.png ...
        -a ESModel2A1.png ...
        -a ESModel2B0.png ...
        -a ESModel2B1.png ...
        -a ExpControl0.png ...
        -a ExpControl1.png ...
        -a ExpSetup0.png ...
        -a ExpSetup1.png ...
        -a ExpSite0.png ...
        -a ExpSite1.png ...
        -a FreeVibration.png ...
        -a GreyGradient.png ...
        -a GroundMotions0.png ...
        -a GroundMotions1.png ...
        -a InitialConditions0.png ...
        -a InitialConditions1.png ...
        -a Loading0.png ...
        -a Loading1.png ...
        -a Local0.png ...
        -a Local1.png ...
        -a Model1A0.png ...
        -a Model1A1.png ...
        -a Model2A0.png ...
        -a Model2A1.png ...
        -a Model2B0.png ...
        -a Model2B1.png ...
        -a MTSMetal.png ...
        -a MTSWhite.png ...
        -a Pause0.png ...
        -a Pause1.png ...
        -a PEERBoldMetal.png ...
        -a PEERBoldWhite.png ...
        -a Question0.png ...
        -a Question1.png ...
        -a RealController0.png ...
        -a RealController1.png ...
        -a Simulation0.png ...
        -a Simulation1.png ...
        -a Start0.png ...
        -a Start1.png ...
        -a Stop0.png ...
        -a Stop1.png ...
        -a Structure0.png ...
        -a Structure1.png ...
        -a /Users/Andreas/OpenSees/lib/OpenFresco.dylib ...
        -a /Users/Andreas/OpenSees/bin/OpenSees
end
