%CREATEEXECUTABLE to create a standalone executable of the OpenFresco GUI
% CreateExecutable
%
% Written: Andreas Schellenberg (andreas.schellenberg@gmx.net)
% Created: 09/10
% Revision: A
%
% $Revision: $
% $Date: $
% $URL: $

% clean start
clear all; close all; clc;

% get path to OPF directory
pathOPF = pwd;
pathOPF = pathOPF(1:end-11);
cd(pathOPF);

% update PragmaList
UpdatePragmaList(pathOPF);

% set directory for src
pathSRC = fullfile(pathOPF,'Deployment','src');

% change the current directory
cd(pathSRC);

% invoke MATLAB to C/C++ compiler
if ispc
   mcc -mv GUI_Template.m ...
      -a ResponseSpectraElastic.mexw32 ...
      -a TCPSocket.mexw32 ...
      -a Metal.jpg ...        % ..\Buttons\
      -a Analysis0.png ...
      -a Analysis1.png ...
      -a ControlPoint0.png ...
      -a ControlPoint1.png ...
      -a ExpControl0.png ...
      -a ExpControl1.png ...
      -a ExpSetup0.png ...
      -a ExpSetup1.png ...
      -a FreeVibration.png ...
      -a greyGradient.png ...
      -a GroundMotions0.png ...
      -a GroundMotions1.png ...
      -a InitialConditions0.png ...
      -a InitialConditions1.png ...
      -a Loading0.png ...
      -a Loading1.png ...
      -a Model1A0.png ...
      -a Model1A1.png ...
      -a Model2A0.png ...
      -a Model2A1.png ...
      -a Model2B0.png ...
      -a Model2B1.png ...
      -a Pause0.png ...
      -a Pause1.png ...
      -a Question0.png ...
      -a Question1.png ...
      -a RealController0.png ...
      -a RealController1.png ...
      -a Simulation0.png ...
      -a Simulation1.png ...
      -a Start0.png ...
      -a Start1.png ...
      -a Stop0.png ...
      -a Stop1.png ...
      -a Structure0.png ...
      -a Structure1.png ...
      -a Dscoml32.dll ...     % ..\WIN32\bin
      -a genutil.dll ...
      -a libeay32.dll ...
      -a Link.dll ...
      -a mts32olv.dll ...
      -a MtsCsiCom.dll ...
      -a mtslibXml2.dll ...
      -a mtsvw001.dll ...
      -a OpenFresco.exe ...
      -a Pnpscr.dll ...
      -a PNPSCRD.dll ...
      -a Rt.dll ...
      -a rtnote.dll ...
      -a ssleay32.dll ...
      -a taskfinder.dll ...
      -a xpcapi.dll;
elseif ismac || isunix
   mcc -mv GUI_Template.m ...
      -a ResponseSpectraElastic.mexmaci ...
      -a TCPSocket.mexmaci ...
      -a Metal.jpg ...        % ..\Buttons\
      -a Analysis0.png ...
      -a Analysis1.png ...
      -a ControlPoint0.png ...
      -a ControlPoint1.png ...
      -a ExpControl0.png ...
      -a ExpControl1.png ...
      -a ExpSetup0.png ...
      -a ExpSetup1.png ...
      -a FreeVibration.png ...
      -a greyGradient.png ...
      -a GroundMotions0.png ...
      -a GroundMotions1.png ...
      -a InitialConditions0.png ...
      -a InitialConditions1.png ...
      -a Loading0.png ...
      -a Loading1.png ...
      -a Model1A0.png ...
      -a Model1A1.png ...
      -a Model2A0.png ...
      -a Model2A1.png ...
      -a Model2B0.png ...
      -a Model2B1.png ...
      -a Pause0.png ...
      -a Pause1.png ...
      -a Question0.png ...
      -a Question1.png ...
      -a RealController0.png ...
      -a RealController1.png ...
      -a Simulation0.png ...
      -a Simulation1.png ...
      -a Start0.png ...
      -a Start1.png ...
      -a Stop0.png ...
      -a Stop1.png ...
      -a Structure0.png ...
      -a Structure1.png ...
      -a /Users/Andreas/OpenFresco/SourceCode/trunk/WIN32/bin/OpenFresco ...   % ..\WIN32\bin
      -a Pnpscr.dll;
end