close all;


f = figure;
SS = get(0,'screensize');
w = SS(3);
h = SS(4);
Cdata = imread('globe.jpg');
% Cdata = imagesc(Cdata);
Cdata = imresize(Cdata, [but_height but_width]);
but = uicontrol('Style','pushbutton',...
    'String','User Tips',...
    'Units','normalized',...
    'BackgroundColor',[0.3 0.5 0.7],...
    'Callback','Links(''User Tips'')',...
    'Position',[0.01 0.30 0.9 0.5],...
    'CData',Cdata);


% uicontrol('Style','pushbutton',...
%     'String','User Tips',...
%     'Units','normalized',...
%     'BackgroundColor',[0.3 0.5 0.7],...
%     'Callback','Links(''User Tips'')',...
%     'Position',[0.01 0.30 0.9 0.5]);
% 
% a = axes('Position',[0.01 0.30 0.9 0.5],...
%     'XTickLabel',[],'YTickLabel',[]);
% imagesc(Cdata);

%Notes:
%No map exists for .jpg
%Cannot layer axes on top of uicontrols (buttons) due to 'heavyweight'
%setting

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% axes('Parent',ph_Main,'Position',[0 0 1 1],...
%     'XTickLabel',[],'YTickLabel',[]);
% imagesc(imread('backgroundGradient.png'));