#
# Makefile for gElem
#
# Windows
#
objects = gElem.obj socket.obj socketf.obj
#
#cc = cl
#cc = icl
cc = gcc
#cc = g++
#
#fc = ifort
fc = g77
eElem.exe: $(objects) makefile.win
#	ifort -o gElem $(objects) WS2_32.lib -link
	g77 -o gElem.exe $(objects) -lwsock32
.f.obj:
	$(fc) -c $*.f -o $*.obj
.c.obj:
	$(cc) -c $*.c -o $*.obj
