function GUI_Report(varargin)
% GUI_Report generates a report page which provides a summary of the inputs
% selected

%  Initialization tasks
handles = guidata(gcbf);


%%%%%%%%%%%%%%%
%Create figure%
%%%%%%%%%%%%%%%

%Main Figure
SS = get(0,'screensize');
f_Analysis = figure('Visible','on','Name','Report',...
    'NumberTitle','off',...
    'MenuBar','none', ...
    'Color',[1 1 1],...
    'Position',[SS(3)/3-25,SS(4)/8,SS(3)/2,SS(4)*0.75]);

%Toolbar
set(f_Analysis,'Toolbar','figure');
Toolbar_handles = findall(gcf);
delete(Toolbar_handles([3:14 17:18]));
set(Toolbar_handles(15), 'TooltipString', 'Print Report');
set(Toolbar_handles(16), 'TooltipString', 'Save Report');

%Report
Report(1) = uicontrol(f_Analysis,'Style','text',...
            'Units','normalized',...
            'BackgroundColor',[1 1 1],...
            'FontSize',20,...
            'Position',[0.2 0.8 0.6 0.15],...
            'String','OpenFresco Test Setup Summary');
Report(2) = uicontrol(f_Analysis,'Style','text',...
            'Units','normalized',...
            'BackgroundColor',[1 1 1],...
            'FontSize',10,...
            'Position',[0.02 0 0.3 0.8],...
            'String',{['Model Mass:    ' num2str(handles.Model.M)], 
            ['       Model Type:    ' get(get(handles.Structure(2), 'SelectedObject'),'String')]});

end