function GUI_ErrorMonitors(varargin)
% GUI_ErrorMonitors defines the layout of the error monitors page

% Check if window already exists
if ~isempty(findobj('Tag','ErrMon'))
    figure(findobj('Tag','ErrMon'));
    return
end

% Initialization tasks
handles = guidata(gcbf);

% find longest motion
tEnd = 0.0;
for mo=1:length(handles.GM.dt)
    tEndi = handles.GM.scalet{mo}(end);
    if tEndi > tEnd
        tEnd = tEndi;
    end
end

%%%%%%%%%%%%%%%
%Create figure%
%%%%%%%%%%%%%%%

%Main Figure
SS = get(0,'screensize');
f_ErrorMon = figure('Visible','on','Name','Error Monitors',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Tag','ErrMon',...
    'Color',[0.3 0.5 0.7],...
    'Position',[SS(3)*0.12,0,SS(3)*0.88,SS(4)]);

%Toolbar
set(f_ErrorMon,'Toolbar','figure');
Toolbar_handles = findall(gcf);
delete(Toolbar_handles([3:14 17:18]));
set(Toolbar_handles(15), 'TooltipString', 'Print Window');
set(Toolbar_handles(16), 'TooltipString', 'Save Window');
StdMenu(1) = uimenu('Position',1,'Label','MATLAB Menu');
StdMenu(2) = uimenu(StdMenu(1),'Position',1,'Label','Turn on', ...
   'Callback','set(gcf,''MenuBar'',''figure'');');
StdMenu(3) = uimenu(StdMenu(1),'Position',2,'Label','Turn off', ...
   'Callback','set(gcf,''MenuBar'',''none'');');


if strcmp(handles.Model.Type, '1 DOF')
    %1 DOF Case
    
    %Title
    st_ErrorMonitors_title = uicontrol(f_ErrorMon,'Style','text',...
        'String','Error Monitors',...
        'FontSize',20,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'Units','normalized',...
        'Position',[0.3 0.87 0.4 0.1]);
    
    %DOF 1 Figures
    a_ErrorMonitors_eX = axes('Parent',f_ErrorMon,...
        'Tag','EM1e',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.74 0.92 0.13],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_eX,'t (s)');
    ylabel(a_ErrorMonitors_eX,'error (in.)');
    a_ErrorMonitors_efX = axes('Parent',f_ErrorMon,...
        'Tag','EM1ffte',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.54 0.92 0.13]);
    grid('on');
    xlabel(a_ErrorMonitors_efX,'f (Hz)');
    ylabel(a_ErrorMonitors_efX,'fft (in./s)');
    a_ErrorMonitors_ddX = axes('Parent',f_ErrorMon,...
        'Tag','EM1MeasCmd',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.07 0.42 0.41]);
    grid('on');
    xlabel(a_ErrorMonitors_ddX,'dcmd (in.)');
    ylabel(a_ErrorMonitors_ddX,'dmeas (in.)');
    a_ErrorMonitors_etX = axes('Parent',f_ErrorMon,...
        'Tag','EM1track',...
        'NextPlot','replacechildren',...
        'Position',[0.56 0.07 0.42 0.41],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_etX,'t (s)');
    ylabel(a_ErrorMonitors_etX,'TI (in.^2)');
    
else
    %2 DOF Case
    set(f_ErrorMon,'Position',[SS(3)*0.12,0,SS(3)*0.88,SS(4)]);
    
    %Title
    st_ErrorMonitors_title = uicontrol(f_ErrorMon,'Style','text',...
        'String','Error Monitors',...
        'FontSize',20,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'Units','normalized',...
        'Position',[0.3 0.92 0.4 0.05]);
    %DOF 1 Figures
    st_ErrorMonitors_X = uicontrol(f_ErrorMon,'Style','text',...
        'Units','normalized',...
        'FontSize',15,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'String','DOF 1',...
        'Position',[0.26 0.85 0.1 0.05]);
    a_ErrorMonitors_eX = axes('Parent',f_ErrorMon,...
        'Tag','EM1e',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.72 0.43 0.13],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_eX,'t (s)');
    ylabel(a_ErrorMonitors_eX,'error (in.)');    
    a_ErrorMonitors_efX = axes('Parent',f_ErrorMon,...
        'Tag','EM1ffte',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.52 0.43 0.13]);
    grid('on');
    xlabel(a_ErrorMonitors_efX,'f (Hz)');
    ylabel(a_ErrorMonitors_efX,'fft (in./s)');
    a_ErrorMonitors_ddX = axes('Parent',f_ErrorMon,...
        'Tag','EM1MeasCmd',...
        'NextPlot','replacechildren',...
        'Position',[0.06 0.08 0.19 0.38]);
    grid('on');
    xlabel(a_ErrorMonitors_ddX,'dcmd (in.)');
    ylabel(a_ErrorMonitors_ddX,'dmeas (in.)');
    a_ErrorMonitors_etX = axes('Parent',f_ErrorMon,...
        'Tag','EM1track',...
        'NextPlot','replacechildren',...
        'Position',[0.3 0.08 0.19 0.38],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_etX,'t (s)');
    ylabel(a_ErrorMonitors_etX,'TI (in.^2)');
    
    %DOF 2 Figures
    st_ErrorMonitors_Y = uicontrol(f_ErrorMon,'Style','text',...
        'Units','normalized',...
        'FontSize',15,...
        'ForegroundColor',[1 1 1],...
        'BackgroundColor',[0.3 0.5 0.7],...
        'String','DOF 2',...
        'Position',[0.72 0.85 0.1 0.05]);
    a_ErrorMonitors_eY = axes('Parent',f_ErrorMon,...
        'Tag','EM2e',...
        'NextPlot','replacechildren',...
        'Position',[0.55 0.72 0.43 0.13],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_eY,'t (s)');
    ylabel(a_ErrorMonitors_eY,'error (in.)');
    a_ErrorMonitors_efY = axes('Parent',f_ErrorMon,...
        'Tag','EM2ffte',...
        'NextPlot','replacechildren',...
        'Position',[0.55 0.52 0.43 0.13]);
    grid('on');
    xlabel(a_ErrorMonitors_efY,'f (Hz)');
    ylabel(a_ErrorMonitors_efY,'fft (in./s)');
    a_ErrorMonitors_ddY = axes('Parent',f_ErrorMon,...
        'Tag','EM2MeasCmd',...
        'NextPlot','replacechildren',...
        'Position',[0.55 0.08 0.19 0.38]);
    grid('on');
    xlabel(a_ErrorMonitors_ddY,'dcmd (in.)');
    ylabel(a_ErrorMonitors_ddY,'dmeas (in.)');
    a_ErrorMonitors_etY = axes('Parent',f_ErrorMon,...
        'Tag','EM2track',...
        'NextPlot','replacechildren',...
        'Position',[0.79 0.08 0.19 0.38],...
        'XLimMode','manual','Xlim',[0.0 tEnd]);
    grid('on');
    xlabel(a_ErrorMonitors_etY,'t (s)');
    ylabel(a_ErrorMonitors_etY,'TI (in.^2)');
end
