function GUI_AnalysisControls(varargin)
% GUI_StructuralOutput provides layout of the GUI structural output page

% Check if window already exists
if ~isempty(findobj('Tag','AnalysisControls'))
    figure(findobj('Tag','AnalysisControls'));
    return
end

%  Initialization tasks
handles = guidata(gcbf);

panel_color = [0.3 0.5 0.7];%Replace with handles.panelColor

%Main Figure
f_AnalysisControls = figure('Visible','on','Name','Analysis Controls',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Tag','AnalysisControls',...
    'Color',[0.3 0.5 0.7],...
    'Resize','off',...
    'Position',[handles.Store.SS(3)*0.01,handles.Store.SS(4)*0.71,handles.Store.SS(3)*0.10,handles.Store.SS(4)*0.27]);



% handles.Sidebar(3) = uibuttongroup('Parent',f_AnalysisControls,...
%     'BackgroundColor',panel_color,...
%     'Visible','on',...
%     'Tag','ControlPanel',...
%     'Position',[0.03 .03 .94 .94]);
%          handles.Sidebar(4) = uicontrol(handles.Sidebar(3),'Style','togglebutton',...
%              'String','Start',...
%              'Units','normalized',...
%              'Tag','StartControl',...
%              'Position',[0.08 0.66 0.84 0.3],...
%              'CData',startButton);
%          handles.Sidebar(5) = uicontrol(handles.Sidebar(3),'Style','togglebutton',...
%              'String','Pause',...
%              'Units','normalized',...
%              'Tag','PauseControl',...
%              'Position',[0.08 0.34 0.84 0.3],...
%              'CData',pauseButton);
%          handles.Sidebar(6) = uicontrol(handles.Sidebar(3),'Style','togglebutton',...
%              'String','Stop',...
%              'Units','normalized',...
%              'Tag','StopControl',...
%              'Position',[0.08 0.03 0.84 0.3],...
%              'CData',stopButton);
%          align([handles.Sidebar(4) handles.Sidebar(5) handles.Sidebar(6)],'None','Fixed',3);
%          set(handles.Sidebar(3),'SelectionChangeFcn','Analysis(''choose option'')');
%          set(handles.Sidebar(3),'SelectedObject',[]);

handles.Sidebar(3) = uibuttongroup('Parent',f_AnalysisControls,...
    'BackgroundColor',panel_color,...
    'Visible','on',...
    'Tag','ControlPanel',...
    'Position',[0.03 .03 .94 .94]);
         handles.Sidebar(4) = uicontrol(handles.Sidebar(3),'Style','togglebutton',...
             'String','Start',...
             'Units','normalized',...
             'Tag','StartControl',...
             'Position',[0.08 0.66 0.84 0.3],...
             'CData',handles.Store.analysisBut2);
         handles.Sidebar(5) = uicontrol(handles.Sidebar(3),'Style','togglebutton',...
             'String','Pause',...
             'Units','normalized',...
             'Tag','PauseControl',...
             'Position',[0.08 0.34 0.84 0.3],...
             'CData',handles.Store.analysisBut2);
         handles.Sidebar(6) = uicontrol(handles.Sidebar(3),'Style','togglebutton',...
             'String','Stop',...
             'Units','normalized',...
             'Tag','StopControl',...
             'Position',[0.08 0.03 0.84 0.3],...
             'CData',handles.Store.analysisBut2);
         align(handles.Sidebar(4:6),'None','Fixed',3);
         set(handles.Sidebar(3),'SelectionChangeFcn','Analysis(''choose option'')');
         set(handles.Sidebar(3),'SelectedObject',[]);
         
%Update handles structure
guidata(gcbf, handles);

end
