function SplashScreen(action)
%SPLASHSCREEN to display the OpenFrescoExpress splash screen
% SplashScreen(action)
%
% action : switch with following possible values
%             'startup'  to show splash screen during startup
%             'about'    to show splash screen from the help menu
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                          OpenFresco Express                          %%
%%    GUI for the Open Framework for Experimental Setup and Control     %%
%%                                                                      %%
%%   (C) Copyright 2011, The Pacific Earthquake Engineering Research    %%
%%            Center (PEER) & MTS Systems Corporation (MTS)             %%
%%                         All Rights Reserved.                         %%
%%                                                                      %%
%%     Commercial use of this program without express permission of     %%
%%                 PEER and MTS is strictly prohibited.                 %%
%%     See Help -> OpenFresco Express Disclaimer for information on     %%
%%   usage and redistribution, and for a DISCLAIMER OF ALL WARRANTIES.  %%
%%                                                                      %%
%%   Developed by:                                                      %%
%%     Andreas Schellenberg (andreas.schellenberg@gmail.com)            %%
%%     Carl Misra (carl.misra@gmail.com)                                %%
%%     Stephen A. Mahin (mahin@berkeley.edu)                            %%
%%                                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% $Revision$
% $Date$
% $URL$

if ~isempty(findobj('Tag','SplashScreen'))
    figure(findobj('Tag','SplashScreen'));
    return
end

% show splash screen
SS = get(0,'screensize');
ver = fgetl(fopen('OPFE_Version.txt'));
if ispc
    Width = 0.8*0.81*0.92*SS(3);
    Height = 0.8*0.9*0.88*SS(4);
    Position = [0.254*SS(3) 0.186*SS(4) Width Height];
else
    Width = 0.84*0.81*0.92*SS(3);
    Height = 0.81*0.9*0.88*SS(4);
    Position = [0.24*SS(3) 0.186*SS(4) Width Height];
end
if strcmp(action,'startup')
    Position(1) = (SS(3)-Width)/2;
end

% create window
figure('NumberTitle','off',...
    'Color','w',...
    'MenuBar','none',...
    'Tag','SplashScreen',...
    'Position',Position);

uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.1 0.75 0.8 0.2], ...
    'String','OpenFresco Express', ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.50,'FontName','Arial',...
    'BackgroundColor','w','ForegroundColor',rand(3,1),'Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.1 0.773 0.8 0.05], ...
    'String',['Release ',ver,': May 2012'], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.65,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor','r','Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.1 0.51 0.8 0.2], ...
    'String',sprintf('Developed by'),...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.15,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor','k','Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.06 0.495 0.28 0.15], ...
    'String',sprintf('Andreas Schellenberg, Ph.D., P.E.\nDep. of Civil and Env. Eng.\nUniversity of California, Berkeley'),...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.177,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.36 0.495 0.28 0.15], ...
    'String',sprintf('Carl Misra, M.S.\nDep. of Civil and Env. Eng.\nUniversity of California, Berkeley'),...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.177,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.664 0.495 0.28 0.15], ...
    'String',sprintf('Stephen Mahin, Ph.D.\nDep. of Civil and Env. Eng.\nUniversity of California, Berkeley'),...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.177,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.1 0.36 0.8 0.1], ...
    'String',sprintf('OpenFresco Express is supported by funds from'), ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.3,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor','k','Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.1 0.35 0.8 0.05], ...
    'String',sprintf('The Pacific Earthquake Engineering Research Center (PEER)'), ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.55,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.1 0.0 0.8 0.05], ...
    'String',sprintf('(C) Copyright 2011, PEER. All Rights Reserved.'),...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.5,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor','k','Horizontal','center');

% load PEER logo
h = axes('Position',[0.39 0.10 0.22 0.22],...
    'Color','white','XTick',[],'YTick',[]);
PEER = imread(which('PEERBoldWhite.png'));
image(PEER);
axis equal; axis off;
set(get(h,'Children'),'ButtonDownFcn','Links(''PEER'');');

if strcmp(action,'startup')
    set(findobj('Tag','SplashScreen'),'CloseRequestFcn','');
    figure(findobj('Tag','SplashScreen'));
    pause(3.0);
    delete(findobj('Tag','SplashScreen'));
end
