function SplashScreen(action)
%SPLASHSCREEN to display the OpenFrescoExpress splash screen
% SplashScreen(action)
%
% action : switch with following possible values
%             'startup'  to show splash screen during startup
%             'about'    to show splash screen from the help menu
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                          OpenFresco Express                          %%
%%    GUI for the Open Framework for Experimental Setup and Control     %%
%%                                                                      %%
%%   (C) Copyright 2011, The Pacific Earthquake Engineering Research    %%
%%            Center (PEER) & MTS Systems Corporation (MTS)             %%
%%                         All Rights Reserved.                         %%
%%                                                                      %%
%%     Commercial use of this program without express permission of     %%
%%                 PEER and MTS is strictly prohibited.                 %%
%%     See Help -> OpenFresco Express Disclaimer for information on     %%
%%   usage and redistribution, and for a DISCLAIMER OF ALL WARRANTIES.  %%
%%                                                                      %%
%%   Developed by:                                                      %%
%%     Andreas Schellenberg (andreas.schellenberg@gmail.com)            %%
%%     Carl Misra (carl.misra@gmail.com)                                %%
%%     Stephen A. Mahin (mahin@berkeley.edu)                            %%
%%                                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% $Revision$
% $Date$
% $URL$

if ~isempty(findobj('Tag','SplashScreen'))
    figure(findobj('Tag','SplashScreen'));
    return
end

% get version, revision and date
fid = fopen('OPFE_Version.txt');
version = textscan(fgetl(fid),'%*s%*s%s');
revision = textscan(fgetl(fid),'%*s%s');
token = textscan(fgetl(fid),'%s');
date = datestr(token{1}{2},'mmmm yyyy');
fclose(fid);

% show splash screen
SS = get(0,'screensize');
if ispc
    Width = 0.8*0.81*0.92*SS(3);
    Height = 0.8*0.9*0.88*SS(4);
    Position = [0.254*SS(3) 0.186*SS(4) Width Height];
else
    Width = 0.84*0.81*0.92*SS(3);
    Height = 0.81*0.9*0.88*SS(4);
    Position = [0.24*SS(3) 0.186*SS(4) Width Height];
end
if strcmp(action,'startup')
    Position(1) = (SS(3)-Width)/2;
end

% create window
figure('NumberTitle','off', ...
    'Color','w', ...
    'MenuBar','none', ...
    'Tag','SplashScreen', ...
    'Position',Position);
opfColor = rand(1,3);
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.0 0.75 0.565 0.2], ...
    'String','OpenFresco', ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.50,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',0.75*opfColor,'Horizontal','right', ...
    'Enable','inactive','ButtonDownFcn','Links(''OpenFrescoExpress'');');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.565 0.75 0.435 0.2], ...
    'String','Express', ...
    'FontUnits','normalized','FontWeight','bold','FontAngle','italic','FontSize',0.50,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',opfColor,'Horizontal','left', ...
    'Enable','inactive','ButtonDownFcn','Links(''OpenFrescoExpress'');');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.0 0.773 1.0 0.05], ...
    'String',['Release ',version{1}{1},' (Build ',revision{1}{1},'), ',date], ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.65,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor','r','Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.0 0.51 1.0 0.2], ...
    'String','Developed by',...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.15,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor','k','Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.06 0.495 0.28 0.15], ...
    'String',{'Andreas Schellenberg, Ph.D., P.E.', ...
    'Dep. of Civil and Env. Eng.','University of California, Berkeley'},...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.177,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.36 0.495 0.28 0.15], ...
    'String',{'Carl Misra, M.S.', ...
    'Dep. of Civil and Env. Eng.','University of California, Berkeley'},...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.177,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.664 0.495 0.28 0.15], ...
    'String',{'Stephen Mahin, Ph.D.', ...
    'Dep. of Civil and Env. Eng.','University of California, Berkeley'},...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.177,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.0 0.36 1.0 0.1], ...
    'String','OpenFresco Express is supported by funds from', ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.3,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor','k','Horizontal','center');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.0 0.35 1.0 0.05], ...
    'String','The Pacific Earthquake Engineering Research Center (PEER)', ...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.55,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor',[0,0,0.8],'Horizontal','center', ...
    'Enable','inactive','ButtonDownFcn','Links(''PEER'');');
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.0 0.0 1.0 0.05], ...
    'String','Copyright © 2012, PEER. All Rights Reserved.',...
    'FontUnits','normalized','FontWeight','bold','FontSize',0.5,'FontName','Arial', ...
    'BackgroundColor','w','ForegroundColor','k','Horizontal','center');

% load PEER logo
h = axes('Position',[0.39 0.10 0.22 0.22],...
    'Color','white','XTick',[],'YTick',[]);
PEER = imread(which('PEERBoldWhite.png'));
image(PEER);
axis equal; axis off;
set(get(h,'Children'),'ButtonDownFcn','Links(''PEER'');');

if strcmp(action,'startup')
    set(findobj('Tag','SplashScreen'),'CloseRequestFcn','');
    pause(0.25);
    figure(findobj('Tag','SplashScreen'));
    pause(2.5);
    delete(findobj('Tag','SplashScreen'));
end
